export type Bar = { name: string; city: string; style: string; badge: string };
export type Music = { title: string; artist: string; style: string; energy: number; id?: string; query?: string };
export type Drink = { name: string; base: string; family: string; abv: number; mark: string };
export type StorySeed = { phase: number; tag: string; title: string; text: string };
export type MatchProfile = {
  name: string; gender: "woman" | "man" | "nonbinary"; age: number; city: string; height: number;
  face: string; hair: string; outfit: string; role: string; vibe: "spark" | "mystery" | "chill";
  musicStyles: string[]; musicEnergy: number; favoriteTrack: string;
  drinkFamilies: string[]; favoriteDrink: string; drinkAbv: number;
  conversation: string; boundary: string; meetScene: string;
};

export const BARS: Bar[] = [
  { name: "INS 复兴公园", city: "上海", style: "多空间夜生活综合体", badge: "人气地标" },
  { name: "Pony Up", city: "上海", style: "现代鸡尾酒", badge: "亚洲 50 #19 · 2026" },
  { name: "Hope & Sesame 庙前冰室", city: "广州", style: "Speakeasy / 创意调酒", badge: "亚洲 50 #1 · 2026" },
  { name: "MO Bar Shenzhen", city: "深圳", style: "酒店鸡尾酒吧", badge: "亚洲 50 #5 · 2026" },
  { name: "Obsidian Bar", city: "深圳", style: "当代鸡尾酒", badge: "亚洲 50 #10 · 2026" },
  { name: "CMYK", city: "长沙", style: "色彩实验调酒", badge: "亚洲 50 #27 · 2026" },
  { name: "Ralph's Bar", city: "成都", style: "叙事鸡尾酒", badge: "亚洲 50 #28 · 2026" },
  { name: "Tiao", city: "北京", style: "现代中式调酒", badge: "亚洲 50 #50 · 2026" },
  { name: "Speak Low", city: "上海", style: "多层 Speakeasy", badge: "国际榜单常客" },
  { name: "Sober Company", city: "上海", style: "餐饮与鸡尾酒", badge: "国际榜单常客" },
  { name: "The Union Trading Company", city: "上海", style: "美式鸡尾酒吧", badge: "亚洲榜历史上榜" },
  { name: "EPIC", city: "上海", style: "高能量鸡尾酒", badge: "城市精选" },
  { name: "The Odd Couple", city: "上海", style: "经典与未来主义", badge: "城市精选" },
  { name: "Healer", city: "上海", style: "中式风味调酒", badge: "城市精选" },
  { name: "Senator Saloon", city: "上海", style: "威士忌 / 复古酒馆", badge: "城市精选" },
  { name: "Long Bar · The PuLi", city: "上海", style: "酒店长吧", badge: "城市精选" },
  { name: "Bar SanYou", city: "广州", style: "中国烈酒鸡尾酒", badge: "城市精选" },
  { name: "Spin", city: "广州", style: "当代鸡尾酒", badge: "城市精选" },
  { name: "Janes + Hooch", city: "北京", style: "工业风鸡尾酒", badge: "城市精选" },
  { name: "Capital Spirits", city: "北京", style: "白酒吧", badge: "城市精选" },
  { name: "The Tiki Bungalow", city: "北京", style: "Tiki 热带调酒", badge: "城市精选" },
  { name: "Great Leap Brewing", city: "北京", style: "精酿啤酒", badge: "城市精选" },
  { name: "Bar Leone", city: "香港", style: "意式社区鸡尾酒", badge: "亚洲 50 #3 · 2026" },
  { name: "Gokan", city: "香港", style: "日式风味实验", badge: "亚洲 50 #22 · 2026" },
  { name: "Coa", city: "香港", style: "龙舌兰 / Mezcal", badge: "亚洲 50 #24 · 2026" },
  { name: "Mius", city: "香港", style: "沉浸式鸡尾酒", badge: "亚洲 50 #36 · 2026" },
  { name: "Argo", city: "香港", style: "未来风味酒店吧", badge: "亚洲 50 #37 · 2026" },
  { name: "Montana", city: "香港", style: "古巴风格鸡尾酒", badge: "亚洲 50 #47 · 2026" },
  { name: "Penicillin", city: "香港", style: "可持续鸡尾酒", badge: "亚洲 50 #49 · 2026" },
  { name: "The St. Regis Bar", city: "澳门", style: "酒店鸡尾酒吧", badge: "亚洲 50 #45 · 2026" },
];

// All profiles below are fictional adults created for the game. They do not represent real people.
export const MATCH_PROFILES: MatchProfile[] = [
  { name:"林妍",gender:"woman",age:26,city:"上海",height:168,face:"偏椭圆脸、细长杏眼、平直眉、柔和鼻梁、唇峰清晰",hair:"下颌线短发，深棕色",outfit:"黑色无袖上衣、银色耳饰、低跟短靴",role:"展览项目经理",vibe:"mystery",musicStyles:["House","Disco House","Tech House","French House"],musicEnergy:4,favoriteTrack:"Talk To You",drinkFamilies:["苦甜经典","低度开胃","现代苦甜"],favoriteDrink:"Negroni",drinkAbv:24,conversation:"会从 DJ 的过渡方式聊到最近看过的展览，不抢话，但会追问细节。",boundary:"慢热；靠近前会明确询问，偏好先交换歌单。",meetScene:"她在吧台另一端辨认出同一段采样，等你看过来才举杯示意。" },
  { name:"陈穗",gender:"woman",age:24,city:"广州",height:163,face:"圆脸、内双上扬眼、自然弯眉、小巧鼻尖、饱满下唇",hair:"高马尾，带一点自然卷",outfit:"短款夹克、宽腿裤、彩色运动鞋",role:"建筑设计师",vibe:"spark",musicStyles:["Amapiano","Afrobeats","Afropop","Amapiano Pop"],musicEnergy:5,favoriteTrack:"Kakalika",drinkFamilies:["龙舌兰长饮","清爽长饮","无酒精"],favoriteDrink:"Paloma",drinkAbv:12,conversation:"擅长用一个很普通的问题打开话题，聊城市空间时语速会明显变快。",boundary:"只接受清楚回应；喝到第二杯会主动换水。",meetScene:"她刚帮一群朋友拍完合照，转身问你要不要一起听副歌。" },
  { name:"周岚",gender:"woman",age:28,city:"深圳",height:172,face:"长椭圆脸、深眼窝杏眼、浓淡适中的挑眉、直鼻、薄厚均衡唇",hair:"锁骨直发，中分",outfit:"深灰西装、白色背心、窄框眼镜",role:"产品研究员",vibe:"mystery",musicStyles:["Neo-Soul","Alternative R&B","Alté","R&B"],musicEnergy:2,favoriteTrack:"Earrings",drinkFamilies:["自然葡萄酒","纯饮烈酒","咖啡鸡尾酒"],favoriteDrink:"Natural Red Wine",drinkAbv:13,conversation:"先观察，再从一句歌词谈到人的选择；不喜欢被连续追问私人信息。",boundary:"偏好安静区交流，明确拒绝被拍照。",meetScene:"她在窗边给朋友发到家提醒，手机扣下后才和你开始聊天。" },
  { name:"叶澄",gender:"woman",age:27,city:"北京",height:166,face:"心形脸、圆润眼型、略粗平眉、鼻梁柔直、微笑唇",hair:"耳下短卷发",outfit:"旧皮衣、乐队 T 恤、直筒牛仔裤",role:"纪录片剪辑师",vibe:"chill",musicStyles:["Indie Folk","Alternative Rock","Pop Rock","华语 Indie Rock"],musicEnergy:3,favoriteTrack:"爱人错过",drinkFamilies:["日式长饮","威士忌酸酒","无酒精"],favoriteDrink:"Highball",drinkAbv:10,conversation:"不制造热闹，喜欢交换具体的电影和现场演出记忆。",boundary:"朋友同行；任何单独转场都要先发定位。",meetScene:"她借给你充电线，等手机重新亮起后才问你是不是第一次来。" },
  { name:"Kiki",gender:"woman",age:25,city:"成都",height:170,face:"鹅蛋脸、单眼皮长眼、细弯眉、圆润鼻头、上唇偏薄",hair:"黑色长发，低马尾",outfit:"米白针织上衣、红色高跟鞋、复古手袋",role:"品牌文案",vibe:"chill",musicStyles:["Mandopop","City Pop","Dream Pop","Synthpop"],musicEnergy:3,favoriteTrack:"红色高跟鞋",drinkFamilies:["花香经典","起泡果味","无酒精"],favoriteDrink:"Aviation",drinkAbv:22,conversation:"会认真听完一句话再回应，擅长把尴尬改写成轻松的玩笑。",boundary:"更愿意约白天见，不接受酒后仓促承诺。",meetScene:"她发现你们同时跟唱了同一句，笑着问你更喜欢现场版还是录音室版。" },
  { name:"唐夏",gender:"woman",age:29,city:"香港",height:175,face:"偏方脸、上扬杏眼、清晰挑眉、立体鼻梁、丰润唇形",hair:"湿发感背梳短发",outfit:"墨绿色衬衫、黑色长裙、金色戒指",role:"餐饮顾问",vibe:"spark",musicStyles:["Latin House","Reggaeton","Reggaeton Pop","Global Pop"],musicEnergy:5,favoriteTrack:"Jamaican (Bam Bam)",drinkFamilies:["龙舌兰品鉴","龙舌兰酸酒","热带现代经典"],favoriteDrink:"Margarita",drinkAbv:22,conversation:"会从杯中的酸度聊到旅行，但不会用职业知识压住别人的感受。",boundary:"只和判断清醒的人发展亲密互动。",meetScene:"她把端错的酒递回服务员，和你同时说了句没关系。" },
  { name:"程野",gender:"man",age:28,city:"上海",height:182,face:"偏方脸、窄长内双、浓直眉、直鼻、嘴角平直",hair:"利落短发，侧分",outfit:"深色衬衫、宽松西裤、机械表",role:"声音设计师",vibe:"mystery",musicStyles:["House","Tech House","Progressive House","Electroclash"],musicEnergy:5,favoriteTrack:"Free Your Mind",drinkFamilies:["苦甜经典","威士忌经典","现代苦甜"],favoriteDrink:"Boulevardier",drinkAbv:25,conversation:"会先聊音响和节拍，再慢慢转向工作之外的生活，不用夸张语气制造熟悉感。",boundary:"不劝酒；对方换水时也会同步降速。",meetScene:"他站在音响覆盖较弱的位置，给你让出更靠里的座位。" },
  { name:"陈述",gender:"man",age:26,city:"北京",height:178,face:"椭圆脸、圆润双眼皮、自然平眉、鼻尖偏圆、笑时露出浅酒窝",hair:"微卷中短发",outfit:"棕色夹克、素色 T 恤、帆布鞋",role:"播客制作人",vibe:"chill",musicStyles:["Indie Folk","Heartland Rock","华语 Indie Rock","Folk Pop"],musicEnergy:2,favoriteTrack:"Doors",drinkFamilies:["酸酒","威士忌酸酒","精酿啤酒"],favoriteDrink:"Whiskey Sour",drinkAbv:19,conversation:"问题具体但不审问，喜欢听别人讲一件最近真正开心的小事。",boundary:"偏好朋友在附近；拒绝时会立即退回普通社交距离。",meetScene:"他捡到你的杯垫，先问是不是你的，再聊起上面的那句歌词。" },
  { name:"沈岸",gender:"man",age:30,city:"深圳",height:185,face:"长脸、深眼窝、平直浓眉、较高鼻梁、薄唇",hair:"极短发",outfit:"灰黑西装外套、圆领上衣、干净皮鞋",role:"城市规划师",vibe:"mystery",musicStyles:["Neo-Soul","Alternative R&B","Jazz","Alté"],musicEnergy:2,favoriteTrack:"NOBLE",drinkFamilies:["日式长饮","纯饮烈酒","自然葡萄酒"],favoriteDrink:"Highball",drinkAbv:10,conversation:"语速慢，擅长把抽象话题落到一个具体街区和一段步行经验。",boundary:"明确区分酒局热度与真实意愿，偏好留联系方式后再决定。",meetScene:"他从露台回来时扶住快合上的门，却没有默认要和你同行。" },
  { name:"吴漾",gender:"man",age:24,city:"广州",height:176,face:"圆方脸、单眼皮、微挑眉、短鼻梁、饱满下唇",hair:"自然卷寸头",outfit:"彩色针织衫、工装裤、球鞋",role:"运动摄影师",vibe:"spark",musicStyles:["Afrobeats","Amapiano","Afropop","Latin Afrobeats"],musicEnergy:5,favoriteTrack:"Raindance",drinkFamilies:["清爽长饮","朗姆长饮","无酒精"],favoriteDrink:"Mojito",drinkAbv:13,conversation:"热情但会观察反馈，聊舞步时更像邀请而不是考试。",boundary:"不拍未同意的人；对方没有回应就不会继续推进。",meetScene:"他正把相机收进包里，确认不拍脸后才问你要不要加入舞圈。" },
  { name:"Leon",gender:"man",age:29,city:"香港",height:180,face:"心形脸、细长眼、修整弯眉、直鼻、唇峰清楚",hair:"中长发后束",outfit:"奶油色西装、黑色背心、细链项链",role:"酒店品牌经理",vibe:"chill",musicStyles:["K-Pop Crossover","City Pop","Nu-Disco","Disco Pop"],musicEnergy:4,favoriteTrack:"APT.",drinkFamilies:["无酒精","起泡果味","低度开胃"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,conversation:"能自然聊流行文化，也愿意承认不知道，不靠消费标签判断人。",boundary:"整晚 0%；亲密互动前会再次确认对方是否清醒。",meetScene:"他点了无酒精酒，却认真比较三种植物香气，邀请你一起闻香。" },
  { name:"杨序",gender:"man",age:27,city:"长沙",height:173,face:"偏方脸、长眼型、粗平眉、鼻梁中等、宽唇",hair:"短碎发",outfit:"宽肩飞行夹克、银色戒指、黑色运动鞋",role:"独立厂牌运营",vibe:"spark",musicStyles:["Hip-Hop","华语 Hip-Hop","Dance Pop","Funk Pop"],musicEnergy:5,favoriteTrack:"大展鸿图",drinkFamilies:["中国白酒","咸鲜鸡尾酒","无酒精"],favoriteDrink:"Baijiu",drinkAbv:42,conversation:"会聊歌词和方言，但明确把高度酒当作慢饮品鉴，不用拼酒证明关系。",boundary:"高酒精选择只品一小杯，之后改喝水。",meetScene:"他听见你认出一段中文采样，回头确认后才加入话题。" },
  { name:"北屿",gender:"nonbinary",age:26,city:"上海",height:174,face:"窄椭圆脸、上扬眼、细直眉、小巧直鼻、唇形偏薄",hair:"银灰色齐耳短发",outfit:"解构衬衫、宽腿裤、几何耳夹",role:"互动艺术创作者",vibe:"mystery",musicStyles:["Electropop","Synthpop","Electroclash","Indietronica"],musicEnergy:4,favoriteTrack:"Self Aware",drinkFamilies:["无酒精","花香经典","草本短饮"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,conversation:"关注声音与身体距离，喜欢谈空间如何改变人的行为。",boundary:"先确认称呼与代词；不把暧昧等同于身体接触。",meetScene:"北屿在光影装置旁停下，问你觉得它像海浪还是呼吸。" },
  { name:"阿岑",gender:"nonbinary",age:28,city:"成都",height:171,face:"圆润鹅蛋脸、内双圆眼、自然弯眉、圆鼻尖、微笑唇",hair:"黑色中长卷发",outfit:"复古针织背心、白衬衫、乐福鞋",role:"书店策划",vibe:"chill",musicStyles:["Neo-Soul","City Pop","Indie Folk","Dream Pop"],musicEnergy:2,favoriteTrack:"BIRDS OF A FEATHER",drinkFamilies:["自然葡萄酒","咖啡鸡尾酒","无酒精"],favoriteDrink:"Natural Red Wine",drinkAbv:13,conversation:"能在热闹中保留安静，喜欢交换书、歌和城市散步路线。",boundary:"不接受突然拍照或公开发布互动内容。",meetScene:"阿岑在吧台读完一页才合上书，确认你也读过同一位作者。" },
];

const search = (title: string, artist: string) => `${title} ${artist}`;
export const MUSIC: Music[] = [
  { title:"New Religion",artist:"Bebe Rexha, Faithless",style:"House",energy:4,id:"2Lb9ww5vZAnveWnrFQfAKR" },
  { title:"Talk To You",artist:"ANOTR, 54 Ultra",style:"Disco House",energy:4,id:"0kl6Ozan3fuUdCl6TlB15v" },
  { title:"DANCE...",artist:"Slayyyter",style:"Electroclash",energy:5,id:"5rfOARz6QO73wPATyMtQQZ" },
  { title:"Kakalika",artist:"DopeNation",style:"Amapiano",energy:5,id:"1p5F0slR5AF49EDX5o125x" },
  { title:"Freakin’ Out",artist:"Dexter and The Moonrocks",style:"Alternative Rock",energy:3,id:"2SaWT781xr3hHLdbVt5DB7" },
  { title:"Babydoll",artist:"Dominic Fike",style:"Indie Pop",energy:2,id:"7yNf9YjeO5JXUE3JEBgnYc" },
  { title:"Choosin’ Texas",artist:"Ella Langley",style:"Country Pop",energy:3,id:"7scFxt9VhL4FJwuPSfRlfN" },
  { title:"Bangaranga",artist:"DARA",style:"Dance Pop",energy:5,id:"6SvlfrQYzUsW5UQUpUpy26" },
  { title:"Raindance",artist:"Dave, Tems",style:"Afrobeats",energy:4,id:"3oTuTpF1F3A7rEC6RKsMRz" },
  { title:"Janice STFU",artist:"Drake",style:"Hip-Hop",energy:4,id:"514joG57v4yKTsfQmz7stz" },
  { title:"drop dead",artist:"Olivia Rodrigo",style:"Pop Rock",energy:4,id:"6gkbtMtioHgtyGjrMel6ei" },
  { title:"Dracula · JENNIE Remix",artist:"Tame Impala, JENNIE",style:"Psychedelic Pop",energy:4,id:"5yvVYFDUpbnjcnRBgjwTzM" },
  { title:"Jamaican (Bam Bam)",artist:"HUGEL, SOLTO",style:"Latin House",energy:5,id:"7e4zDInS6tA2jwzphvs2Ay" },
  { title:"CHÉVERE",artist:"ARIA VEGA, Ryan Castro",style:"Latin Afrobeats",energy:5,id:"3CBEVPwR3kUXDoTx1lqFUQ" },
  { title:"Earrings",artist:"Malcolm Todd",style:"Neo-Soul",energy:2,id:"0eAuGrXyGFYwur9ARUe7LJ" },
  { title:"Boston",artist:"STELLA LEFTY",style:"Folk Pop",energy:2,id:"36idurZmYRjJ56KQ8JD9bN" },
  { title:"hate that i made you love me",artist:"Ariana Grande",style:"Power Pop",energy:4,id:"20jbSiX29FDX4oQxBXyUEi" },
  { title:"Kingdom of Fear",artist:"Cameron Whitcomb",style:"Americana",energy:3,id:"4Es6f0zquGHCrv9Hespx9W" },
  { title:"NOBLE",artist:"F3miii",style:"Alté",energy:4,id:"2LSmH4vxyRhkJ2pPqcmkXw" },
  { title:"L.U.C.K.Y",artist:"Fcukers",style:"Electropop",energy:5,id:"1KoTSKG0vs2vbzMvrbpWjp" },
  { title:"Mexico Honey",artist:"Kacey Musgraves",style:"Country",energy:2,id:"7xKr077iMufVJwge6aO9xJ" },
  { title:"Maladie",artist:"Mauvais djo",style:"Afropop",energy:4,id:"4zPb5wNcdTy15BgBvRVNYM" },
  { title:"Doors",artist:"Noah Kahan",style:"Indie Folk",energy:2,id:"3iU2qsthCTo5EeTE03l3Si" },
  { title:"KOKO",artist:"Omar Courtz",style:"Reggaeton",energy:5,id:"1tz7RZirwiuaJw2p0jbdHb" },
  { title:"Girl Like Me",artist:"PinkPantheress",style:"UK Garage",energy:4,id:"7aYGCP34Xo6XujY7Ix1DxB" },
  { title:"Free Your Mind",artist:"Prospa, Cloonee",style:"Tech House",energy:5,id:"6TWbY1dq8eYtFiMiGdBlOa" },
  { title:"Rein Me In",artist:"Sam Fender, Olivia Dean",style:"Heartland Rock",energy:3,id:"7MZHqgTVTnN6xZGYAcEEAf" },
  { title:"Self Aware",artist:"Temper City",style:"Synthpop",energy:4,id:"4qW3BbQAwZsrnu8a3ZRdyT" },
  { title:"Midnight Sun",artist:"Zara Larsson",style:"Europop",energy:5,id:"7N1GSHGlLwXY3lN5gv3QLV" },
  { title:"Dai Dai",artist:"Shakira, Burna Boy",style:"Global Pop",energy:5,id:"4TSStAtQq6HWYwa46elQCS" },
  { title:"大展鸿图",artist:"揽佬SKAI ISYOURGOD, AR刘夫阳",style:"华语 Hip-Hop",energy:5,id:"0hEWvzkgbI301JZj947gFz" },
  { title:"APT.",artist:"ROSÉ, Bruno Mars",style:"K-Pop Crossover",energy:5,query:search("APT.","ROSÉ Bruno Mars") },
  { title:"Die With A Smile",artist:"Lady Gaga, Bruno Mars",style:"Pop Ballad",energy:2,query:search("Die With A Smile","Lady Gaga Bruno Mars") },
  { title:"BIRDS OF A FEATHER",artist:"Billie Eilish",style:"Dream Pop",energy:2,query:search("BIRDS OF A FEATHER","Billie Eilish") },
  { title:"Espresso",artist:"Sabrina Carpenter",style:"Disco Pop",energy:4,query:search("Espresso","Sabrina Carpenter") },
  { title:"Blinding Lights",artist:"The Weeknd",style:"Synthwave",energy:5,query:search("Blinding Lights","The Weeknd") },
  { title:"Levitating",artist:"Dua Lipa",style:"Nu-Disco",energy:5,query:search("Levitating","Dua Lipa") },
  { title:"One Kiss",artist:"Calvin Harris, Dua Lipa",style:"Dance / Electronic",energy:5,query:search("One Kiss","Calvin Harris Dua Lipa") },
  { title:"Titanium",artist:"David Guetta, Sia",style:"EDM",energy:5,query:search("Titanium","David Guetta Sia") },
  { title:"Levels",artist:"Avicii",style:"Progressive House",energy:5,query:search("Levels","Avicii") },
  { title:"Midnight City",artist:"M83",style:"Indietronica",energy:4,query:search("Midnight City","M83") },
  { title:"Get Lucky",artist:"Daft Punk, Pharrell Williams",style:"French House",energy:4,query:search("Get Lucky","Daft Punk") },
  { title:"Starboy",artist:"The Weeknd, Daft Punk",style:"Alternative R&B",energy:4,query:search("Starboy","The Weeknd Daft Punk") },
  { title:"Water",artist:"Tyla",style:"Amapiano Pop",energy:4,query:search("Water","Tyla") },
  { title:"Calm Down",artist:"Rema, Selena Gomez",style:"Afrobeat Pop",energy:3,query:search("Calm Down","Rema Selena Gomez") },
  { title:"Despacito",artist:"Luis Fonsi, Daddy Yankee",style:"Reggaeton Pop",energy:5,query:search("Despacito","Luis Fonsi") },
  { title:"Uptown Funk",artist:"Mark Ronson, Bruno Mars",style:"Funk Pop",energy:5,query:search("Uptown Funk","Mark Ronson Bruno Mars") },
  { title:"红色高跟鞋",artist:"蔡健雅",style:"Mandopop",energy:3,query:search("红色高跟鞋","蔡健雅") },
  { title:"爱人错过",artist:"告五人",style:"华语 Indie Rock",energy:4,query:search("爱人错过","告五人") },
  { title:"Plastic Love",artist:"Mariya Takeuchi",style:"City Pop",energy:3,query:search("Plastic Love","Mariya Takeuchi") },
];

export const DRINKS: Drink[] = [
  {name:"Negroni",base:"Gin · Vermouth · Campari",family:"苦甜经典",abv:24,mark:"N"},
  {name:"Americano",base:"Campari · Vermouth · Soda",family:"低度开胃",abv:12,mark:"A"},
  {name:"Dry Martini",base:"Gin · Dry Vermouth",family:"烈酒短饮",abv:29,mark:"M"},
  {name:"Espresso Martini",base:"Vodka · Coffee · Liqueur",family:"咖啡鸡尾酒",abv:20,mark:"E"},
  {name:"Cosmopolitan",base:"Vodka · Cranberry · Citrus",family:"果味短饮",abv:19,mark:"C"},
  {name:"Margarita",base:"Tequila · Lime · Triple Sec",family:"龙舌兰酸酒",abv:22,mark:"MG"},
  {name:"Paloma",base:"Tequila · Grapefruit · Soda",family:"龙舌兰长饮",abv:12,mark:"P"},
  {name:"Mojito",base:"Rum · Mint · Lime · Soda",family:"清爽长饮",abv:13,mark:"MJ"},
  {name:"Daiquiri",base:"Rum · Lime · Sugar",family:"朗姆酸酒",abv:21,mark:"D"},
  {name:"Old Fashioned",base:"Whiskey · Sugar · Bitters",family:"威士忌经典",abv:28,mark:"OF"},
  {name:"Manhattan",base:"Rye · Vermouth · Bitters",family:"威士忌短饮",abv:27,mark:"MH"},
  {name:"Whiskey Sour",base:"Whiskey · Lemon · Sugar",family:"酸酒",abv:19,mark:"WS"},
  {name:"Highball",base:"Whisky · Soda",family:"日式长饮",abv:10,mark:"HB"},
  {name:"Boulevardier",base:"Bourbon · Campari · Vermouth",family:"苦甜威士忌",abv:25,mark:"B"},
  {name:"Aperol Spritz",base:"Aperol · Prosecco · Soda",family:"意式开胃",abv:9,mark:"AS"},
  {name:"French 75",base:"Gin · Lemon · Sparkling",family:"起泡鸡尾酒",abv:15,mark:"75"},
  {name:"Tom Collins",base:"Gin · Lemon · Soda",family:"金酒长饮",abv:12,mark:"TC"},
  {name:"Gin Fizz",base:"Gin · Lemon · Soda",family:"Fizz",abv:13,mark:"GF"},
  {name:"Moscow Mule",base:"Vodka · Ginger Beer · Lime",family:"姜味长饮",abv:11,mark:"MM"},
  {name:"Bloody Mary",base:"Vodka · Tomato · Spice",family:"咸鲜鸡尾酒",abv:10,mark:"BM"},
  {name:"Pisco Sour",base:"Pisco · Lime · Egg White",family:"南美酸酒",abv:20,mark:"PS"},
  {name:"Caipirinha",base:"Cachaça · Lime · Sugar",family:"巴西经典",abv:22,mark:"CA"},
  {name:"Mai Tai",base:"Rum · Curaçao · Orgeat",family:"Tiki",abv:23,mark:"MT"},
  {name:"Piña Colada",base:"Rum · Coconut · Pineapple",family:"热带奶油",abv:13,mark:"PC"},
  {name:"Cuba Libre",base:"Rum · Cola · Lime",family:"朗姆长饮",abv:12,mark:"CL"},
  {name:"Long Island Iced Tea",base:"Five Spirits · Citrus · Cola",family:"高酒精长饮",abv:24,mark:"LI"},
  {name:"Sidecar",base:"Cognac · Triple Sec · Lemon",family:"白兰地酸酒",abv:24,mark:"SC"},
  {name:"Sazerac",base:"Cognac/Rye · Absinthe · Bitters",family:"新奥尔良经典",abv:32,mark:"SZ"},
  {name:"Mint Julep",base:"Bourbon · Mint · Sugar",family:"碎冰长饮",abv:22,mark:"MJ"},
  {name:"Penicillin",base:"Scotch · Lemon · Honey · Ginger",family:"现代经典",abv:20,mark:"PN"},
  {name:"Paper Plane",base:"Bourbon · Amaro · Aperol · Lemon",family:"现代苦甜",abv:19,mark:"PP"},
  {name:"Aviation",base:"Gin · Maraschino · Violet · Lemon",family:"花香经典",abv:22,mark:"AV"},
  {name:"Last Word",base:"Gin · Chartreuse · Maraschino · Lime",family:"草本短饮",abv:24,mark:"LW"},
  {name:"Vesper",base:"Gin · Vodka · Lillet",family:"高酒精 Martini",abv:31,mark:"V"},
  {name:"Clover Club",base:"Gin · Raspberry · Lemon · Egg White",family:"莓果酸酒",abv:18,mark:"CC"},
  {name:"Bellini",base:"Prosecco · Peach",family:"起泡果味",abv:8,mark:"BL"},
  {name:"Mimosa",base:"Sparkling Wine · Orange",family:"早午餐起泡",abv:7,mark:"MI"},
  {name:"Pornstar Martini",base:"Vodka · Passion Fruit · Sparkling",family:"热带现代经典",abv:17,mark:"PM"},
  {name:"Irish Coffee",base:"Irish Whiskey · Coffee · Cream",family:"热饮",abv:11,mark:"IC"},
  {name:"Dark ’n’ Stormy",base:"Dark Rum · Ginger Beer",family:"朗姆姜味",abv:13,mark:"DS"},
  {name:"IPA",base:"Hops · Malt · Yeast",family:"精酿啤酒",abv:6,mark:"IPA"},
  {name:"Lager",base:"Malt · Hops",family:"淡色拉格",abv:5,mark:"LG"},
  {name:"Stout",base:"Roasted Malt · Hops",family:"黑啤",abv:6,mark:"ST"},
  {name:"Champagne",base:"Traditional Method Sparkling Wine",family:"起泡酒",abv:12,mark:"CH"},
  {name:"Natural Red Wine",base:"Grapes · Wild Fermentation",family:"自然葡萄酒",abv:13,mark:"NW"},
  {name:"Junmai Sake",base:"Rice · Koji · Water",family:"清酒",abv:15,mark:"SA"},
  {name:"Baijiu",base:"Sorghum · Qu",family:"中国白酒",abv:42,mark:"白"},
  {name:"Single Malt Whisky",base:"Malted Barley · Oak",family:"纯饮烈酒",abv:43,mark:"SM"},
  {name:"Agave Spirit Flight",base:"Tequila · Mezcal",family:"龙舌兰品鉴",abv:40,mark:"AG"},
  {name:"Zero-proof Tonic",base:"Botanical · Citrus · Tonic",family:"无酒精",abv:0,mark:"0%"},
];

const P0 = [
  "FIRST LIGHT|雨水留在门外|你推开{bar}的门，伞尖滴下三滴水。寄存处的人递来号码牌，{track}的低频从地板升到锁骨，第一杯{drink}刚好在吧台亮起。",
  "WRONG DOOR|入口藏在意料之外|你绕过一扇没有招牌的门才找到{bar}。调酒师像认出老客一样点头，问你今晚想被热闹接住，还是先留一块安静。",
  "ELEVATOR|电梯停在陌生楼层|门打开时整面镜子先映出{name}。{city}的灯被留在背后，前方是一条只够两人并肩的暗廊。",
  "COAT CHECK|一张号码牌|外套被挂进第 27 格。你突然意识到，离开时必须回来取它——这让今晚像是被悄悄加了一个结尾。",
  "FIRST SIP|第一口比预想更复杂|{drink}先是酸，随后有一小段烟熏。你放慢速度，决定今晚每杯酒之间都加一杯水。",
  "WINDOW SEAT|窗边唯一空位|你坐下时正好看见一辆末班公交驶过。玻璃把{track}的鼓点震成细纹，城市在另一侧无声移动。",
  "DRESS CODE|鞋跟与门槛|门口没有评判你的穿着，只提醒你台阶很暗。你走进去，发现真正吸引视线的是你不慌不忙的步子。",
  "BAR STOOL|第七码高脚凳|吧台只剩一个位置，左右各坐着一位互不认识的人。你把手机扣在桌面，给今晚留出第一次真正抬头。",
  "BIRTHDAY|隔壁桌的生日|陌生人的生日歌只唱到一半就笑场。有人把一小块蛋糕分给你，奶油甜味意外地配上了{drink}。",
  "POWER CUT|灯暗了一秒|全场灯光短暂熄灭，只有应急出口和几十块手机屏幕亮着。灯回来时，所有人像共同保守了一个一秒钟的秘密。",
  "VINYL CRACKLE|唱针落下|DJ没有立刻接强拍，而是让黑胶的底噪先铺满房间。你听见身后有人准确说出这首歌的采样来源。",
  "NO SIGNAL|手机失去信号|地下空间没有网络。地图、消息和外卖同时离线，你只好记住出口，也更认真地看清眼前的人。",
  "MIRROR LINE|镜子里的第二入口|你以为前面没有路，直到镜中有人从暗门走出。{bar}像故意把现实折了一次。",
  "FRAGRANCE|一阵雪松香|有人经过时带起雪松与柑橘的气味，没有回头。几秒后，你在酒单里看到同样的风味组合。",
  "FIRST WATER|先来一杯水|调酒师没有急着推酒单，而是先放下一杯常温水。这份不动声色的照顾，让你决定在这里多待一会。",
  "QUEUE FRIEND|排队时的临时同盟|前面的人替你扶住快要合上的门。你们只聊了两分钟，却交换了各自在{city}最喜欢的深夜面馆。",
  "PHOTO BOOTH|无人使用的拍照亭|帘子半开，屏幕停在倒计时“3”。你可以拍一张只给自己看的照片，也可以把它留给下一位陌生人。",
  "EMPTY TABLE|被预留的空桌|服务员确认三次后说预订客人取消了。整张桌子归你，像城市今晚突然多给了一点空间。",
  "SOUND CHECK|低频还没完全打开|你到得比人群早，DJ正在校准监听。没有高潮的二十分钟反而让你看见工作人员如何把夜晚一块块搭起来。",
  "CITY VIEW|四十二层的风|电梯速度让耳膜轻轻一紧。落地窗外，车流像缓慢的电路；杯中的冰比整座城市更响。",
  "SECRET MENU|酒单最后一页|最后一页没有价格，只写三种情绪：靠近、转身、暂停。调酒师说它们都可以做成无酒精版本。",
  "LOST EARRING|地面的一点银光|你捡到一只小耳环交给吧台。十分钟后失主回来道谢，认真记住了你的名字。",
  "FLOWER SELLER|门外最后一束花|进门前有人问你要不要买今晚最后一束雏菊。你买下后把一半留给门口辛苦站岗的人。",
  "RESERVATION|名字被正确念出|接待准确念出{name}，没有问多余的问题。被认真对待的第一分钟，让肩膀先松了下来。",
  "FRESH ICE|第一块透明冰|冰块落杯的声音干净得像按下开始键。你看一眼时间：22:47，故事从这里正式计时。",
];
const P1 = [
  "EYE CONTACT|吧台另一端的两秒|你抬头时和一个人对视了两秒。对方先移开，又在{track}副歌开始时举杯示意；这可能是搭讪，也可能只是礼貌。",
  "SONG QUESTION|“你也喜欢这首？”|旁边的人指了指音箱问你。你听得出这不是背熟的开场白，因为对方还准确说出了制作人的名字。",
  "BARTENDER STORY|杯垫背面的地图|调酒师翻过杯垫，画出三条夜宵路线，并圈出自己下班后会去的一家。城市忽然有了私人注脚。",
  "OLD FRIEND|熟悉名字从身后响起|多年没见的同学认出你，身边还带着两个新朋友。过去与现在被迫坐到同一张桌上，但没有谁急着叙旧。",
  "WRONG DRINK|端错的一杯|服务员把一杯粉色长饮放到你面前，立刻发现桌号错了。真正的主人走来，两个人同时说“没关系”，然后笑了。",
  "DANCE CIRCLE|舞池让出一个圆|几个人为即兴舞步留出空间，没有起哄，也没有推人进去。有人向你伸手，但停在足够远的位置等你决定。",
  "QUIET CORNER|安静没有被打断|人群绕过你所在的角落。你听完整首{track}，发现独处并不是故事缺席，而是一种清楚的选择。",
  "PHONE CHARGER|借到最后一根线|邻座把充电线分给你一半，说自己还有 38%。你们把两部手机放在一起，却先聊起各自最近想逃离的通知。",
  "COASTER NOTE|杯垫上的一句话|上一位客人在杯垫背面写：“今晚别急着证明什么。”你不知道是谁留下，却决定把它收进口袋。",
  "GROUP PHOTO|被邀请按快门|一群朋友请你帮忙拍合照。你连续按了三张，第四张时他们把你也拉进画面，但先问你是否愿意。",
  "ACCENT|从口音猜城市|有人准确听出你不是本地人，却没有追问来历，只推荐一首属于他故乡的歌。你们交换的第一样东西是一段声音。",
  "ICE BREAKER|一块滚到脚边的冰|调酒师做 flair 时冰块意外落地，严肃的全场一起笑了。完美被打破后，陌生人之间反而更容易说话。",
  "BOOK ON BAR|吧台上的小说|有人在吵闹里读一本书，书脊是你也读过的作者。你可以谈书，也可以尊重这份独处。",
  "JACKET MIXUP|拿错的同款外套|两件黑色外套几乎一模一样。你们翻口袋确认归属，一个装着薄荷糖，一个装着电影票根。",
  "DRINK QUESTION|“这杯是什么味道？”|对方没有问你一个人来不来，只认真问{drink}。话题停留在风味，没有越过你没开放的边界。",
  "DJ REQUEST|一张点歌纸条|DJ 收下纸条却不保证会放。四十分钟后熟悉的前奏响起，递纸条的人隔着人群找到你的眼睛。",
  "LANGUAGE SWAP|一句不熟练的中文|旅行者努力念对{drink}的名字，你帮他纠正声调；作为交换，他教你一句自己家乡的晚安。",
  "RAIN RETURN|雨又开始了|窗边的人发现你没带伞，提出离开时可以送到地铁口，同时补了一句：“如果你觉得方便的话。”",
  "POLAROID|一张即时照片|摄影师问能否拍下你手边的杯子，不拍脸。成像后把唯一一张底片交给你，没有索要账号。",
  "SEAT OFFER|有人让出靠里位置|不是因为身高或性别，只因为那里更安静。微小的体贴没有附带谈话义务。",
  "NOISE APP|分贝提醒|手表震动提醒环境过响。旁边的人看到后指向走廊尽头的安静区，你们并肩走过去，仍保留一臂距离。",
  "PET VIDEO|最普通的破冰|陌生人给同伴看猫打翻水杯的视频，你没忍住笑出声。对方问要不要再看一个——艳遇可能从最不浪漫的东西开始。",
  "SAME ORDER|两杯同名酒|你和邻座同时点了{drink}。调酒师把杯子并排放下，你们各自先喝水，再比较第一口的感受。",
  "COMPLIMENT|一个具体的赞美|有人说喜欢你的耳饰配色，而不是评价身体。具体、轻巧、不索取回应，这句搭讪因此显得舒服。",
  "DECLINE|被好好接住的拒绝|有人邀请你去舞池，你说想先坐会儿。对方只回“当然”，没有追问。边界被尊重后，空气没有变坏。",
];
const P2 = [
  "DEEP TALK|话题越过寒暄|你们从{track}聊到最近一次想换城市的念头。对方没有急着给建议，只问：“那件事对你最难的是什么？”",
  "WATER BREAK|第二杯是气泡水|你把酒换成水，对方也跟着换了。清醒没有让暧昧降温，反而让每句话都更容易被记住。",
  "DANCE ASK|先问，再靠近|对方在音乐变快时问：“一起跳吗？不想也没关系。”伸出的手停在半空，选择权完整地留给你。",
  "FRIEND CHECK|朋友发来一个句号|这是你们约定的安全暗号。你回复定位和“都好”，顺手确认回程路线，心情因此更放松。",
  "EX TEXT|旧消息突然亮起|一个曾经很重要的人发来“睡了吗”。你没有立刻回复，把手机翻面，决定先完成眼前真实的夜晚。",
  "SPILLED DRINK|杯子被碰倒|酒液越过桌面，对方先拿纸巾护住你的手机，而不是责怪谁。狼狈被处理得很轻，距离也因此真实了一点。",
  "SLOW SONG|DJ 突然降速|强拍被一首慢歌切开，人群有些不知所措。你们可以继续跳、退到边缘，或各自给彼此空间。",
  "ROOFTOP AIR|天台的风让人清醒|你们走到户外区，门仍在视线内。{city}凌晨的风吹散酒气，谈话第一次不需要靠得很近。",
  "BAR SNACK|最后一份热食|厨房只剩一份小食，你们分开装在两个盘子里。分享不等于亏欠，账单也各自清楚。",
  "NAME AGAIN|再次确认名字|对方在嘈杂里重新问了一遍{name}，并认真念对。被记住的不是照片，而是你刚才讲的那件小事。",
  "BOUNDARY|手停在肩膀前|对方想替你拂去纸屑，却在碰到前先示意。你点头或摇头都很自然，暧昧不需要偷走同意。",
  "TWO TRUTHS|两个真话，不玩谎言|你们各说一件最近让自己开心的小事。不靠窥探隐私，话题也能逐渐靠近。",
  "MUSIC SHARE|一边耳机|安静区听不见 DJ，你们用一副耳机播放{track}。对方先擦了耳塞，再问你愿不愿意共享另一边。",
  "BAD JOKE|一个很冷的笑话|笑话并不好笑，但讲完后对方先自嘲。你真正喜欢的是那份不端着，而不是包袱本身。",
  "WORK CALL|突然的工作电话|对方接到紧急电话，回来后坦白今晚状态不适合继续社交。你们互相祝好，没有把中止解释成失败。",
  "LOST FRIEND|帮人找到同伴|一位明显慌张的客人找不到朋友。你和工作人员一起确认安全区域，十分钟后两人重逢，全场压力才松开。",
  "FLOOR CHANGE|换一层声音|你们从电子舞池走到爵士吧台，音量下降后发现彼此说话的速度也慢了。不同音乐像切换了另一条剧情线。",
  "TASTE TEST|盲闻三种香气|调酒师递来柚子、罗勒和烘烤可可让你们猜。答案都错了，但你们记住了彼此第一反应。",
  "SILENCE|十秒钟没人说话|沉默没有被急着填满。你们同时看向舞池，又同时笑了；舒服的空白也是化学反应的一部分。",
  "CHECK SPLIT|账单被自然分开|服务员问是否分单，两个人同时说“分开”。没有试探、没有表演，平等让接下来的靠近更轻松。",
  "COMPLIMENT RETURN|赞美被接住|你说喜欢对方讲故事时会先想两秒。对方没有否定自己，只说谢谢，然后也给你一个具体而不过界的赞美。",
  "PHOTO CONSENT|镜头举起前|朋友想记录舞池，先确认画面里的你是否介意。你可以加入，也可以退到镜头外，两种选择都被立刻接受。",
  "LAST ROUND|不再加酒|酒保提醒这是最后点单。你选择水和一份小食，保留判断力，也让身体跟上今晚的节奏。",
  "METRO CLOCK|末班车倒计时|手机显示还有 23 分钟。你们决定不靠错过交通制造浪漫，先把安全回程放进计划。",
  "ALMOST KISS|距离只剩半步|音乐和人群都像退远了，但没有人默认下一步。一个清楚的问题，比任何突然靠近都更有张力。",
];
const P3 = [
  "ASKED KISS|一句完整的问题|“我可以吻你吗？”问题被清楚说出，答案也有充分空间。无论点头还是说慢一点，这一刻都不需要猜。",
  "DAYLIGHT DATE|约在白天见|你们没有把凌晨的浓度当成承诺，只约了周日下午喝咖啡。能在阳光里继续的可能，显得更可靠。",
  "PLAYLIST|交换歌单|不是微信开场白，而是一张各自十首歌的清单。最后一首都留空，等下一次见面再补。",
  "GOODBYE ALONE|一个人叫车|你在明亮区域确认车牌，把行程分享给朋友。车门关上时没有失落，只有完整结束一晚的踏实。",
  "FRIENDS HOME|和朋友一起离开|你们在门口清点人数、外套和手机。最好的夜晚有时不是艳遇，而是所有人都平安到家。",
  "SUNRISE NOODLES|清晨第一碗面|你们去了调酒师画在杯垫上的店。没有继续喝酒，热汤让每个人慢慢回到真实世界。",
  "SOFT NO|“我想慢一点”|对方说还不想吻，你回答“当然”。边界没有破坏气氛，反而让这段相遇从幻想落到可信。",
  "MUTUAL YES|被回答的靠近|对方看着你点头，先确认彼此都清醒舒服。这个吻很短，像一首歌结束前最后一下鼓点。",
  "NUMBER LOST|号码没有保存成功|回到车上才发现联系人没有同步。遗憾很轻，却让这场相遇保留为一段只属于今晚的电影。",
  "WRONG NUMBER|最后一位写错|第二天消息没有送达。你没有回酒吧寻找，也没有责怪谁；有些故事的价值不靠续集证明。",
  "COAT RETURN|取回第 27 格外套|号码牌完成了使命。工作人员说晚安，你发现口袋里多了一张写着歌曲名的杯垫。",
  "RAIN WALK|共撑一把伞到地铁|伞并不大，你们先问好目的地，再保持舒服的距离。雨声替代低频，谈话终于不用喊。",
  "TAXI SPLIT|不同方向的两辆车|你们没有因为“顺路”勉强同乘。两辆车先后到达，隔着车窗挥手，安全比戏剧性更重要。",
  "NO PROMISE|没有说“永远联系”|你们只说今天很开心。克制的告别没有减少真诚，反而让这晚停在恰好的位置。",
  "VOICE NOTE|到家后的十秒语音|对方只说“我到了，谢谢今晚”。你回复同样简短的一句，确认安全后把手机调成勿扰。",
  "QUIET WIN|没有艳遇的好结局|你认真喝完一杯、听完几首歌，并在想走时离开。不是每个夜晚都要被另一个人证明。",
  "BARTENDER FAREWELL|记住你喝水的人|离开时调酒师把水杯推近，说路上小心。他记住的不是你喝了多少，而是你一直在照顾节奏。",
  "DAWN PHOTO|只拍城市，不拍人|你们在门口拍下四点的街道，没有把彼此放进镜头。照片不公开，先只留在各自手机里。",
  "BREAKFAST GROUP|陌生人变成一桌|最初互不认识的六个人拼桌吃早餐。没人追问关系，大家只认真讨论豆浆该甜还是咸。",
  "FOUND EARRING|耳环回到主人手里|失主在门口追上你，再次道谢。你们没有发展成爱情，却共同完成了一个小小的圆满。",
  "FIRST TRAIN|等到首班地铁|你在便利店买水，坐在明亮窗口等车。耳朵还残留低频，清晨的人群已经开始另一种生活。",
  "BLOCKED CHOICE|主动结束不舒服的对话|当对方开始越界追问，你清楚说不再继续并走向工作人员。故事没有浪漫结尾，但你保护了自己。",
  "STAFF HELP|安全计划被启动|工作人员陪你到等车区并记录异常情况。求助不是扫兴，而是让夜生活值得信任的基础设施。",
  "SECOND CITY|下次在另一座城|你们发现下月都会去同一场音乐节，只约好若行程仍合适就再联系，不提前制造承诺。",
  "MORNING SONG|最后一首成为第一首|回家路上{track}又随机播放。它不再只是热门曲目，而成了你记住{city}这一夜的私人坐标。",
];

const parse = (phase: number, item: string): StorySeed => {
  const [tag, title, text] = item.split("|");
  return { phase, tag, title, text };
};
export const STORY_SEEDS: StorySeed[] = [
  ...P0.map((x) => parse(0, x)), ...P1.map((x) => parse(1, x)),
  ...P2.map((x) => parse(2, x)), ...P3.map((x) => parse(3, x)),
];
