export type Bar = {
  name: string; city: string; style: string; badge: string; description: string;
  atmosphere: string; music: string; signature: string;
  energy: number; social: number; intimacy: number; storyTags: string[];
  sourceLabel: string; sourceUrl: string;
};
export type Music = { title: string; artist: string; style: string; energy: number; description: string; id?: string; query?: string };
export type Drink = { name: string; base: string; family: string; abv: number; mark: string; description: string };
export type StorySeed = { phase: number; tag: string; title: string; text: string };
export type MatchProfile = {
  id: string; gender: "woman" | "man" | "nonbinary"; age: number; city: string; height: number;
  face: string; hair: string; outfit: string; role: string; vibe: "spark" | "mystery" | "chill";
  musicStyles: string[]; musicEnergy: number; favoriteTrack: string;
  drinkFamilies: string[]; favoriteDrink: string; drinkAbv: number;
  conversation: string; boundary: string; meetScene: string;
};

export const BARS: Bar[] = [
  {name:"INS 复兴公园",city:"上海",style:"七层多空间夜生活综合体",badge:"官方地标精选",description:"位于复兴公园，官方资料显示这里横跨七层、集合 20 多个音乐、餐饮、艺术与夜生活空间；同一晚可以从现场流行、Hip-Hop、地下电子切换到更亲密的 lounge。",atmosphere:"人流密集、选择多、转场快，像一座夜间游乐园。",music:"电子、Hip-Hop、现场流行与多元派对",signature:"多场地自由转场",energy:5,social:5,intimacy:2,storyTags:["dance","group","music","explore"],sourceLabel:"INS 官方",sourceUrl:"https://ins.hero.com/"},
  {name:"Hope & Sesame 庙前冰室",city:"广州",style:"粤式 Speakeasy / 现场爵士",badge:"亚洲 50 #1 · 2026",description:"入口藏在传统粤式咖啡店之后，酒单使用澄清、低温浸泡与店内蒸馏等现代技术；更深处还有现场爵士空间。2026 年成为首家登顶亚洲榜单的中国内地酒吧。",atmosphere:"隐藏入口制造悬念，内场克制，爵士区会逐渐升温。",music:"现场爵士与低干扰背景音乐",signature:"粤味创意与冬瓜茶风味长饮",energy:4,social:4,intimacy:4,storyTags:["speakeasy","live","deep","cocktail"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Bar Leone",city:"香港",style:"意式社区鸡尾酒",badge:"亚洲 50 #3 · 2026",description:"以“cocktail popolari——属于大家的鸡尾酒”为核心，用精确而亲切的方式重做意大利经典，配烟熏橄榄与意式熟肉佛卡夏；空间像罗马街区酒吧，轻松但不随便。",atmosphere:"邻里感强、热闹而易加入，适合从吧台闲聊开始。",music:"复古意式流行与轻快背景音乐",signature:"Filthy Martini 与 Yuzu Negroni",energy:4,social:5,intimacy:3,storyTags:["social","food","classic","playful"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"MO Bar Shenzhen",city:"深圳",style:"79 层城市景观酒店吧",badge:"亚洲 50 #5 · 2026",description:"位于 79 层，以深圳天际线、金色时刻窗景和完整的酒店服务为核心；坐窗边适合慢聊，坐吧台则能观看调酒团队协作，代表作包括普洱茶 Negroni。",atmosphere:"高空、开阔、秩序感强，视线交流多于拥挤碰撞。",music:"精致 Lounge、Soul 与柔和电子",signature:"普洱茶 Negroni 与高空日落",energy:3,social:3,intimacy:4,storyTags:["skyline","date","quiet","cocktail"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Obsidian Bar",city:"深圳",style:"双层蒸汽朋克鸡尾酒吧",badge:"亚洲 50 #10 · 2026",description:"两层空间给出两条路线：楼下开放厨房与大桌更适合热闹聚餐，楼上则用天际线、软座和丰富威士忌收藏放慢速度，因此同一目的地可推演出群体或私聊两类故事。",atmosphere:"一楼外向、二楼克制，转场本身就是剧情节点。",music:"现代节拍与深夜 Lounge",signature:"开放厨房、威士忌与双层视野",energy:4,social:4,intimacy:3,storyTags:["group","food","whisky","skyline"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Pony Up",city:"上海",style:"玩乐型当代鸡尾酒",badge:"亚洲 50 #19 · 2026",description:"紧凑的胡桃木空间配一张把鸡尾酒画成游乐设施的卡通地图，白天到深夜均营业；龙井与杨桃 Daiquiri、山茶花 Gin 等本地风味让酒单天然成为开场话题。",atmosphere:"小空间、近距离、带一点美式餐吧的轻松玩心。",music:"轻快 Disco、Funk 与城市流行",signature:"游乐园地图式酒单",energy:4,social:4,intimacy:3,storyTags:["playful","small","food","cocktail"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Gokan",city:"香港",style:"五感与东亚餐酒",badge:"亚洲 50 #22 · 2026",description:"设在昔日冰库空间，以“五感”为名把酒分成甜、酸、辣、苦、鲜五种方向；川味 Mapo Mary 与西瓜咖啡 Fizz 等作品，把菜肴、酒与服务连成完整体验。",atmosphere:"灯光戏剧化但交流克制，适合从风味偏好聊到记忆。",music:"低速电子、Jazz 与精致背景声",signature:"五味菜单与东亚餐酒结合",energy:3,social:4,intimacy:4,storyTags:["deep","food","sensory","cocktail"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Coa",city:"香港",style:"Agave / Mezcal 专门吧",badge:"亚洲 50 #24 · 2026",description:"自 2017 年起专注龙舌兰与 Mezcal，收藏规模和知识深度都很突出；团队强调让新手也能在引导下理解烟熏、植物与产地差异，2026 年获 Legend of the List。",atmosphere:"专业但不端着，吧台问答很容易发展成共同品鉴。",music:"Latin、Funk 与沉稳酒吧背景声",signature:"大规模 Agave 收藏与专业引导",energy:4,social:4,intimacy:3,storyTags:["bartender","tasting","social","agave"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"CMYK",city:"长沙",style:"高能量多房间实验调酒",badge:"亚洲 50 #27 · 2026",description:"名字来自印刷四色，也对应“Countless Memories You Keep”。多房间老宅以颜色、技术型鸡尾酒和持续变化的菜单制造高能量，官方榜单特别强调它适合年轻客人混合与交流。",atmosphere:"多房间、高饱和、越夜越热，群体互动概率高。",music:"Hip-Hop、Dance Pop 与高能电子",signature:"四色概念与湖南城市夜生活",energy:5,social:5,intimacy:2,storyTags:["dance","group","color","explore"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Ralph's Bar",city:"成都",style:"纽约酒馆式威士忌吧",badge:"亚洲 50 #28 · 2026",description:"位于 Ralph Lauren 成都旗舰店楼上，以深木、马术细节与纽约 tavern 气质构成精致而温暖的空间；酒单由 Hope & Sesame 协作开发，重点是美式威士忌与西部风味。",atmosphere:"俱乐部感、坐席主导，适合穿搭话题和慢速约会。",music:"美式经典、Jazz 与低调 Soul",signature:"美式威士忌与马术空间",energy:3,social:3,intimacy:4,storyTags:["date","whisky","quiet","style"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Mius",city:"香港",style:"极简精密鸡尾酒",badge:"亚洲 50 #36 · 2026",description:"仅接受 walk-in，12 款酒每杯不超过六种原料；不锈钢与胡桃木构成安静、收束的室内，2026 年同时获得亚洲榜单最佳酒吧设计奖，重点是克制与精确。",atmosphere:"座位有限、注意力集中，最适合一对一观察与深聊。",music:"极简电子、Ambient 与慢拍 R&B",signature:"六种以内原料的 12 杯菜单",energy:2,social:2,intimacy:5,storyTags:["quiet","small","deep","design"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Argo",city:"香港",style:"海港景观酒店鸡尾酒吧",badge:"亚洲 50 #37 · 2026",description:"像镀金时代的植物温室，面向维港；酒单从香港饮食记忆取材，把奶茶、蛋挞与火锅香料转译成 Punch 和鸡尾酒。景观与本地味道会同时成为谈话线索。",atmosphere:"华丽、开阔、节奏从容，适合正式约会和纪念性片段。",music:"Lounge、Jazz 与现代 Soul",signature:"维港景观与香港味觉记忆",energy:3,social:3,intimacy:5,storyTags:["skyline","date","deep","local"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"The St. Regis Bar",city:"澳门",style:"复古纽约式酒店吧",badge:"亚洲 50 #45 · 2026",description:"以瑞吉品牌的纽约起源为线索，用软座、世纪之交装饰与澳门味道连接两座城市；招牌 Bloody Mary 加入香肠、粉红胡椒、辣椒和黑醋，并搭配迷你蛋挞。",atmosphere:"礼仪感与舒适度并存，适合慢饮、纪念日和安静续聊。",music:"现场感 Jazz、钢琴与经典 Lounge",signature:"澳门风味 Bloody Mary",energy:3,social:3,intimacy:5,storyTags:["hotel","date","quiet","classic"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Montana",city:"香港",style:"七十年代复古鸡尾酒派对",badge:"亚洲 50 #47 · 2026",description:"由 Bar Leone 与 Sips / Boadas 背景团队共同打造，目标是一场似乎不会结束的 1970 年代鸡尾酒派对；经典酒被重新演绎，Daiquiri 甚至装在花形杯中。",atmosphere:"复古、玩闹、外向，陌生人更容易因杯具和造型搭话。",music:"70s Disco、Funk 与 Latin",signature:"七十年代经典重做",energy:5,social:5,intimacy:2,storyTags:["dance","retro","playful","social"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Penicillin",city:"香港",style:"闭环可持续鸡尾酒",badge:"亚洲 50 #49 · 2026",description:"香港首家闭环鸡尾酒吧，强调本地、升级再利用原料和自有发酵室；黑芝麻 Gin、绿豆 Vermouth、乳酸发酵青瓜皮等组合让可持续做法变成可直接讨论的味觉体验。",atmosphere:"实验室感与社区感并存，适合好奇型客人交流制作过程。",music:"Downtempo、实验电子与 Soul",signature:"闭环原料、发酵与升级再利用",energy:3,social:3,intimacy:4,storyTags:["sustainable","bartender","deep","experimental"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"Tiao",city:"北京",style:"胡同叙事双层鸡尾酒吧",badge:"亚洲 50 #50 · 2026",description:"楼下是适合停留的暗色酒吧，楼上露台适合看人与街景；“Worlds Apart”酒单把周边约 450 年的历史转成鸡尾酒叙事，让空间选择直接改变互动方式。",atmosphere:"楼下私密、楼上开放，观察与搭话可以自然切换。",music:"现代中式、Jazz 与柔和电子",signature:"胡同历史叙事酒单",energy:3,social:4,intimacy:4,storyTags:["terrace","peoplewatch","deep","local"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/stories/News/asias-50-best-bars-2026-the-list-revealed.html"},
  {name:"The Opposites",city:"香港",style:"平衡与戏剧双线鸡尾酒",badge:"亚洲 100 #54 · 2026",description:"菜单分成 Balanced 与 Theatrical 两条对照路线，并明确标出 ABV；电影感空间使用低光、深座与黄铜桌面，既能玩有气泡罩的戏剧酒，也能在卡座停留。",atmosphere:"沉浸、低光、玩味，适合从选择差异进入暧昧问答。",music:"电影感电子、Trip-Hop 与爵士",signature:"同一概念的平衡版与戏剧版",energy:3,social:4,intimacy:4,storyTags:["playful","deep","design","choice"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/bars/best-in-asia/list/1-50"},
  {name:"The Savory Project",city:"香港",style:"咸鲜与鲜味鸡尾酒",badge:"亚洲 100 #60 · 2026",description:"由 Coa 团队创立，刻意减少甜味，以菌菇、味噌、香料、白酱油等厨房原料构建咸鲜酒；六边形吧台缩短客人与调酒师距离，也为陌生人之间留下自然视线。",atmosphere:"好奇、互动、吧台中心化，品鉴反应很容易变成共同话题。",music:"Neo-Soul、Funk 与低速 Hip-Hop",signature:"咸鲜、泥土与 Umami 风味",energy:3,social:5,intimacy:3,storyTags:["food","bartender","social","experimental"],sourceLabel:"Asia’s 50 Best Bars",sourceUrl:"https://www.theworlds50best.com/bars/best-in-asia/list/1-50"},
  {name:"Tell Camellia",city:"香港",style:"茶主题现代调酒",badge:"亚洲 100 #81 · 2026",description:"以 Camellia 茶树为概念，将白茶、煎茶、茉莉、乌龙与正山小种等放进现代鸡尾酒；官方酒单同时有 Tea-tails、T-tonic 和经典改编，风味跨度适合做低压力问答。",atmosphere:"隐藏、芳香、专注，茶香让不喝烈酒的人也容易参与讨论。",music:"Jazzhop、Neo-Soul 与精致 Lounge",signature:"全球茶叶与当代鸡尾酒融合",energy:2,social:3,intimacy:5,storyTags:["tea","quiet","deep","tasting"],sourceLabel:"Tell Camellia 官方",sourceUrl:"https://www.tellcamellia.hk/"},
  {name:"Chimney 烟囱",city:"杭州",style:"加州式社区鸡尾酒吧",badge:"亚洲 100 #91 · 2026",description:"2019 年创立于中山中路老建筑，强调社区连接；酒单大量使用龙井、桂花、绍兴酒等本地、当季与传统中国原料，楼上还有“bar within a bar”概念的 Bar Eg.。",atmosphere:"社区感、老建筑与吧台交流并重，适合新朋友自然加入。",music:"Indie、Funk 与城市轻电子",signature:"中国季节原料与社区文化",energy:4,social:5,intimacy:3,storyTags:["community","local","bartender","explore"],sourceLabel:"Asia’s 50 Best Bars / 城市报道",sourceUrl:"https://www.citynewsservice.cn/articles/cns/city-news/quick-news/the-list-chinas-hope-sesame-wins-the-no-1-bar-in-asia-2026-zmppq75m"},
  {name:"Coa Shanghai",city:"上海",style:"大型 Agave 专门吧",badge:"亚洲 100 #95 · 2026",description:"香港 Coa 的上海分店，2024 年迁至复兴中路后继续经营，资料显示收藏近 300 种 Agave 酒；专业引导、烟熏风味与跨楼层探索都能产生“请教—共饮—转场”故事。",atmosphere:"专业、开放、适合边喝边学，聊天通常由产地与风味发起。",music:"Latin、Funk 与低速电子",signature:"近 300 种 Agave 酒收藏",energy:4,social:4,intimacy:3,storyTags:["agave","tasting","explore","bartender"],sourceLabel:"Asia’s 50 Best Bars / 上海指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"Bar Long Fong",city:"北京",style:"中国烈酒与单一产地调酒",badge:"亚洲 100 #96 · 2026",description:"北京的华丽小型鸡尾酒 lounge，强调单一产地原料以及白酒、黄酒等中国烈酒；复杂技术最后要落到“好喝”，小体量坐席让调酒师与客人的交流更直接。",atmosphere:"精致、小型、热度适中，适合约会与风味问答。",music:"现代中式、Jazz 与 Downtempo",signature:"白酒、黄酒和中国单一产地原料",energy:3,social:3,intimacy:5,storyTags:["local","tasting","small","date"],sourceLabel:"Asia’s 50 Best Bars / 城市报道",sourceUrl:"https://www.citynewsservice.cn/articles/cns/city-news/quick-news/the-list-chinas-hope-sesame-wins-the-no-1-bar-in-asia-2026-zmppq75m"},
  {name:"Speak Low",city:"上海",style:"多层隐藏式 Speakeasy",badge:"上海官方城市精选",description:"由 Shingo Gokan 打造，被上海官方城市指南称为推动本地 Speakeasy 潮流的重要场所；隐藏入口和多层空间让“发现下一扇门”成为体验核心。",atmosphere:"神秘、分层、越往里越私密，转场能自然改变谈话深度。",music:"Hip-Hop、Funk、Jazz 与深夜电子",signature:"隐藏入口与多层探索",energy:4,social:4,intimacy:4,storyTags:["speakeasy","explore","deep","music"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"Sober Company",city:"上海",style:"日式四区餐酒空间",badge:"上海官方城市精选",description:"回归 INS 后扩展为约 400 平方米、上下两层和四个区域，从茶主题 Sober Kissa 到居酒屋手卷与鸡尾酒形成连续路线；既可以独处，也可随进程转到更热闹区域。",atmosphere:"日式、复合、可慢可快，不同区域对应不同社交距离。",music:"City Pop、Jazz、House 与日式流行",signature:"四个区域的餐酒转场",energy:4,social:4,intimacy:4,storyTags:["food","explore","date","social"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"Playground",city:"上海",style:"地下 Techno / House 夜店",badge:"上海官方城市精选",description:"位于 INS 地下一层，上海官方指南将它描述为专注 Techno 与 House 的地下夜店；高密度低频、持续混音和舞池身体语言会让故事更偏向舞步、眼神和朋友确认。",atmosphere:"暗、响、强节拍，语言交流较少，非语言反馈更重要。",music:"Techno、House 与地下电子",signature:"高能地下舞池",energy:5,social:4,intimacy:1,storyTags:["dance","music","boundary","group"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"La Fin 2.0",city:"上海",style:"法式未来派派对空间",badge:"上海官方城市精选",description:"位于 INS 六层，保留法式根源，同时用《星际牛仔》式太空酒吧视觉更新派对体验；强造型环境会提升穿搭、合照和主动搭话类情节。",atmosphere:"未来、戏剧、适合打扮，视觉注意力高。",music:"French House、Disco 与 Dance Pop",signature:"太空酒吧视觉与法式派对",energy:5,social:5,intimacy:2,storyTags:["dance","style","photo","playful"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"KEV · Bund 18",city:"上海",style:"外滩未来感屋顶酒吧",badge:"上海官方城市精选",description:"位于外滩十八号顶层，约 565 平方米露台同时观看外滩与陆家嘴；未来主义内装、干邑、威士忌、香槟和视觉型鸡尾酒，让故事更偏景观、拍照与正式邀约。",atmosphere:"高空、开阔、上镜，陌生人常从景观与拍照开始交流。",music:"Lounge、Afro House 与时装感电子",signature:"双岸天际线与大面积露台",energy:4,social:4,intimacy:3,storyTags:["skyline","photo","terrace","date"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"Tearoom by EHB",city:"上海",style:"东方式茶味 Villa 酒吧",badge:"上海官方城市精选",description:"藏在东平路别墅，白天是茶空间、夜晚转为酒吧；11 款以茶味为灵感的创意鸡尾酒从清新、甜润到浓郁，适合用风味选择打开较慢的交流。",atmosphere:"别墅、安静、东方细节丰富，约会和深聊权重高。",music:"Ambient、Jazz 与 Neo-Soul",signature:"茶味鸡尾酒与昼夜转换",energy:2,social:3,intimacy:5,storyTags:["tea","quiet","date","deep"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"HUSH by PH",city:"上海",style:"地下感 Hip-Hop 夜店",badge:"上海官方城市精选",description:"北京 Hip-Hop 热门品牌 PH 的上海分店，位于 INS；金属风管、旧混凝土和地下隧道式灯光把说唱文化与舞池自由感放在前台。",atmosphere:"城市、直接、低光高能，歌词和穿搭是主要搭话入口。",music:"Hip-Hop、Trap、R&B 与 Rap",signature:"地下隧道视觉与 Hip-Hop",energy:5,social:5,intimacy:1,storyTags:["dance","music","style","group"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
  {name:"Culture Club",city:"上海",style:"包容型多元文化舞池",badge:"上海官方城市精选",description:"INS 内强调多元派对文化的空间，舞池不大但氛围活跃、包容；重点不是豪华坐席，而是音乐、身份表达和自由跳舞，因此故事更偏结识新朋友与群体互动。",atmosphere:"包容、紧凑、开放，适合朋友局与低压力加入舞圈。",music:"多元电子、Pop、House 与主题派对",signature:"多元社群与自由舞池",energy:5,social:5,intimacy:2,storyTags:["dance","inclusive","group","community"],sourceLabel:"上海市政府城市指南",sourceUrl:"https://english.shanghai.gov.cn/en-BarsandPubs/20240523/c3dbbb3a8e6a48b4ae1f447502fd1fe9.html"},
];

// All profiles below are fictional adults created for the game. They do not represent real people.
const BASE_MATCH_PROFILES: MatchProfile[] = [
  { id:"F01",gender:"woman",age:26,city:"上海",height:168,face:"偏椭圆脸、细长杏眼、平直眉、柔和鼻梁、唇峰清晰",hair:"下颌线短发，深棕色",outfit:"黑色无袖上衣、银色耳饰、低跟短靴",role:"展览项目经理",vibe:"mystery",musicStyles:["House","Disco House","Tech House","French House"],musicEnergy:4,favoriteTrack:"Talk To You",drinkFamilies:["苦甜经典","低度开胃","现代苦甜"],favoriteDrink:"Negroni",drinkAbv:24,conversation:"会从 DJ 的过渡方式聊到最近看过的展览，不抢话，但会追问细节。",boundary:"慢热；靠近前会明确询问，偏好先交换歌单。",meetScene:"她在吧台另一端辨认出同一段采样，等你看过来才举杯示意。" },
  { id:"F02",gender:"woman",age:24,city:"广州",height:163,face:"圆脸、内双上扬眼、自然弯眉、小巧鼻尖、饱满下唇",hair:"高马尾，带一点自然卷",outfit:"短款夹克、宽腿裤、彩色运动鞋",role:"建筑设计师",vibe:"spark",musicStyles:["Amapiano","Afrobeats","Afropop","Amapiano Pop"],musicEnergy:5,favoriteTrack:"Kakalika",drinkFamilies:["龙舌兰长饮","清爽长饮","无酒精"],favoriteDrink:"Paloma",drinkAbv:12,conversation:"擅长用一个很普通的问题打开话题，聊城市空间时语速会明显变快。",boundary:"只接受清楚回应；喝到第二杯会主动换水。",meetScene:"她刚帮一群朋友拍完合照，转身问你要不要一起听副歌。" },
  { id:"F03",gender:"woman",age:28,city:"深圳",height:172,face:"长椭圆脸、深眼窝杏眼、浓淡适中的挑眉、直鼻、薄厚均衡唇",hair:"锁骨直发，中分",outfit:"深灰西装、白色背心、窄框眼镜",role:"产品研究员",vibe:"mystery",musicStyles:["Neo-Soul","Alternative R&B","Alté","R&B"],musicEnergy:2,favoriteTrack:"Earrings",drinkFamilies:["自然葡萄酒","纯饮烈酒","咖啡鸡尾酒"],favoriteDrink:"Natural Red Wine",drinkAbv:13,conversation:"先观察，再从一句歌词谈到人的选择；不喜欢被连续追问私人信息。",boundary:"偏好安静区交流，明确拒绝被拍照。",meetScene:"她在窗边给朋友发到家提醒，手机扣下后才和你开始聊天。" },
  { id:"F04",gender:"woman",age:27,city:"北京",height:166,face:"心形脸、圆润眼型、略粗平眉、鼻梁柔直、微笑唇",hair:"耳下短卷发",outfit:"旧皮衣、乐队 T 恤、直筒牛仔裤",role:"纪录片剪辑师",vibe:"chill",musicStyles:["Indie Folk","Alternative Rock","Pop Rock","华语 Indie Rock"],musicEnergy:3,favoriteTrack:"爱人错过",drinkFamilies:["日式长饮","威士忌酸酒","无酒精"],favoriteDrink:"Highball",drinkAbv:10,conversation:"不制造热闹，喜欢交换具体的电影和现场演出记忆。",boundary:"朋友同行；任何单独转场都要先发定位。",meetScene:"她借给你充电线，等手机重新亮起后才问你是不是第一次来。" },
  { id:"F05",gender:"woman",age:25,city:"成都",height:170,face:"鹅蛋脸、单眼皮长眼、细弯眉、圆润鼻头、上唇偏薄",hair:"黑色长发，低马尾",outfit:"米白针织上衣、红色高跟鞋、复古手袋",role:"品牌文案",vibe:"chill",musicStyles:["Mandopop","City Pop","Dream Pop","Synthpop"],musicEnergy:3,favoriteTrack:"红色高跟鞋",drinkFamilies:["花香经典","起泡果味","无酒精"],favoriteDrink:"Aviation",drinkAbv:22,conversation:"会认真听完一句话再回应，擅长把尴尬改写成轻松的玩笑。",boundary:"更愿意约白天见，不接受酒后仓促承诺。",meetScene:"她发现你们同时跟唱了同一句，笑着问你更喜欢现场版还是录音室版。" },
  { id:"F06",gender:"woman",age:29,city:"香港",height:175,face:"偏方脸、上扬杏眼、清晰挑眉、立体鼻梁、丰润唇形",hair:"湿发感背梳短发",outfit:"墨绿色衬衫、黑色长裙、金色戒指",role:"餐饮顾问",vibe:"spark",musicStyles:["Latin House","Reggaeton","Reggaeton Pop","Global Pop"],musicEnergy:5,favoriteTrack:"Jamaican (Bam Bam)",drinkFamilies:["龙舌兰品鉴","龙舌兰酸酒","热带现代经典"],favoriteDrink:"Margarita",drinkAbv:22,conversation:"会从杯中的酸度聊到旅行，但不会用职业知识压住别人的感受。",boundary:"只和判断清醒的人发展亲密互动。",meetScene:"她把端错的酒递回服务员，和你同时说了句没关系。" },
  { id:"M01",gender:"man",age:28,city:"上海",height:182,face:"偏方脸、窄长内双、浓直眉、直鼻、嘴角平直",hair:"利落短发，侧分",outfit:"深色衬衫、宽松西裤、机械表",role:"声音设计师",vibe:"mystery",musicStyles:["House","Tech House","Progressive House","Electroclash"],musicEnergy:5,favoriteTrack:"Free Your Mind",drinkFamilies:["苦甜经典","威士忌经典","现代苦甜"],favoriteDrink:"Boulevardier",drinkAbv:25,conversation:"会先聊音响和节拍，再慢慢转向工作之外的生活，不用夸张语气制造熟悉感。",boundary:"不劝酒；对方换水时也会同步降速。",meetScene:"他站在音响覆盖较弱的位置，给你让出更靠里的座位。" },
  { id:"M02",gender:"man",age:26,city:"北京",height:178,face:"椭圆脸、圆润双眼皮、自然平眉、鼻尖偏圆、笑时露出浅酒窝",hair:"微卷中短发",outfit:"棕色夹克、素色 T 恤、帆布鞋",role:"播客制作人",vibe:"chill",musicStyles:["Indie Folk","Heartland Rock","华语 Indie Rock","Folk Pop"],musicEnergy:2,favoriteTrack:"Doors",drinkFamilies:["酸酒","威士忌酸酒","精酿啤酒"],favoriteDrink:"Whiskey Sour",drinkAbv:19,conversation:"问题具体但不审问，喜欢听别人讲一件最近真正开心的小事。",boundary:"偏好朋友在附近；拒绝时会立即退回普通社交距离。",meetScene:"他捡到你的杯垫，先问是不是你的，再聊起上面的那句歌词。" },
  { id:"M03",gender:"man",age:30,city:"深圳",height:185,face:"长脸、深眼窝、平直浓眉、较高鼻梁、薄唇",hair:"极短发",outfit:"灰黑西装外套、圆领上衣、干净皮鞋",role:"城市规划师",vibe:"mystery",musicStyles:["Neo-Soul","Alternative R&B","Jazz","Alté"],musicEnergy:2,favoriteTrack:"NOBLE",drinkFamilies:["日式长饮","纯饮烈酒","自然葡萄酒"],favoriteDrink:"Highball",drinkAbv:10,conversation:"语速慢，擅长把抽象话题落到一个具体街区和一段步行经验。",boundary:"明确区分酒局热度与真实意愿，偏好留联系方式后再决定。",meetScene:"他从露台回来时扶住快合上的门，却没有默认要和你同行。" },
  { id:"M04",gender:"man",age:24,city:"广州",height:176,face:"圆方脸、单眼皮、微挑眉、短鼻梁、饱满下唇",hair:"自然卷寸头",outfit:"彩色针织衫、工装裤、球鞋",role:"运动摄影师",vibe:"spark",musicStyles:["Afrobeats","Amapiano","Afropop","Latin Afrobeats"],musicEnergy:5,favoriteTrack:"Raindance",drinkFamilies:["清爽长饮","朗姆长饮","无酒精"],favoriteDrink:"Mojito",drinkAbv:13,conversation:"热情但会观察反馈，聊舞步时更像邀请而不是考试。",boundary:"不拍未同意的人；对方没有回应就不会继续推进。",meetScene:"他正把相机收进包里，确认不拍脸后才问你要不要加入舞圈。" },
  { id:"M05",gender:"man",age:29,city:"香港",height:180,face:"心形脸、细长眼、修整弯眉、直鼻、唇峰清楚",hair:"中长发后束",outfit:"奶油色西装、黑色背心、细链项链",role:"酒店品牌经理",vibe:"chill",musicStyles:["K-Pop Crossover","City Pop","Nu-Disco","Disco Pop"],musicEnergy:4,favoriteTrack:"APT.",drinkFamilies:["无酒精","起泡果味","低度开胃"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,conversation:"能自然聊流行文化，也愿意承认不知道，不靠消费标签判断人。",boundary:"整晚 0%；亲密互动前会再次确认对方是否清醒。",meetScene:"他点了无酒精酒，却认真比较三种植物香气，邀请你一起闻香。" },
  { id:"M06",gender:"man",age:27,city:"长沙",height:173,face:"偏方脸、长眼型、粗平眉、鼻梁中等、宽唇",hair:"短碎发",outfit:"宽肩飞行夹克、银色戒指、黑色运动鞋",role:"独立厂牌运营",vibe:"spark",musicStyles:["Hip-Hop","华语 Hip-Hop","Dance Pop","Funk Pop"],musicEnergy:5,favoriteTrack:"大展鸿图",drinkFamilies:["中国白酒","咸鲜鸡尾酒","无酒精"],favoriteDrink:"Baijiu",drinkAbv:42,conversation:"会聊歌词和方言，但明确把高度酒当作慢饮品鉴，不用拼酒证明关系。",boundary:"高酒精选择只品一小杯，之后改喝水。",meetScene:"他听见你认出一段中文采样，回头确认后才加入话题。" },
  { id:"X01",gender:"nonbinary",age:26,city:"上海",height:174,face:"窄椭圆脸、上扬眼、细直眉、小巧直鼻、唇形偏薄",hair:"银灰色齐耳短发",outfit:"解构衬衫、宽腿裤、几何耳夹",role:"互动艺术创作者",vibe:"mystery",musicStyles:["Electropop","Synthpop","Electroclash","Indietronica"],musicEnergy:4,favoriteTrack:"Self Aware",drinkFamilies:["无酒精","花香经典","草本短饮"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,conversation:"关注声音与身体距离，喜欢谈空间如何改变人的行为。",boundary:"先确认称呼与代词；不把暧昧等同于身体接触。",meetScene:"匹配对象在光影装置旁停下，问你觉得它像海浪还是呼吸。" },
  { id:"X02",gender:"nonbinary",age:28,city:"成都",height:171,face:"圆润鹅蛋脸、内双圆眼、自然弯眉、圆鼻尖、微笑唇",hair:"黑色中长卷发",outfit:"复古针织背心、白衬衫、乐福鞋",role:"书店策划",vibe:"chill",musicStyles:["Neo-Soul","City Pop","Indie Folk","Dream Pop"],musicEnergy:2,favoriteTrack:"BIRDS OF A FEATHER",drinkFamilies:["自然葡萄酒","咖啡鸡尾酒","无酒精"],favoriteDrink:"Natural Red Wine",drinkAbv:13,conversation:"能在热闹中保留安静，喜欢交换书、歌和城市散步路线。",boundary:"不接受突然拍照或公开发布互动内容。",meetScene:"匹配对象在吧台读完一页才合上书，确认你也读过同一位作者。" },
];

type ExtraProfileSeed = Pick<MatchProfile,"id"|"gender"|"age"|"city"|"height"|"role"|"vibe"|"musicStyles"|"musicEnergy"|"favoriteTrack"|"drinkFamilies"|"favoriteDrink"|"drinkAbv"|"meetScene">;
const EXTRA_PROFILE_SEEDS: ExtraProfileSeed[] = [
  {id:"F07",gender:"woman",age:23,city:"杭州",height:165,role:"视觉设计师",vibe:"mystery",musicStyles:["Dream Pop","Indietronica"],musicEnergy:2,favoriteTrack:"BIRDS OF A FEATHER",drinkFamilies:["花香经典","无酒精"],favoriteDrink:"Clover Club",drinkAbv:18,meetScene:"匹配女生在唱片封面墙前停留，发现你也在看同一张专辑。"},
  {id:"F08",gender:"woman",age:30,city:"南京",height:171,role:"律师",vibe:"chill",musicStyles:["Neo-Soul","Alternative R&B"],musicEnergy:2,favoriteTrack:"Earrings",drinkFamilies:["自然葡萄酒","日式长饮"],favoriteDrink:"Natural Red Wine",drinkAbv:13,meetScene:"匹配女生在安静区给朋友报平安，收起手机后才回应你的问候。"},
  {id:"F09",gender:"woman",age:25,city:"武汉",height:167,role:"独立摄影师",vibe:"spark",musicStyles:["Afrobeats","Amapiano Pop"],musicEnergy:5,favoriteTrack:"Water",drinkFamilies:["清爽长饮","龙舌兰长饮"],favoriteDrink:"Paloma",drinkAbv:12,meetScene:"匹配女生拍完灯光后主动把镜头放下，问你是否也喜欢这段鼓点。"},
  {id:"F10",gender:"woman",age:28,city:"厦门",height:160,role:"咖啡烘焙师",vibe:"chill",musicStyles:["City Pop","Folk Pop"],musicEnergy:3,favoriteTrack:"Plastic Love",drinkFamilies:["咖啡鸡尾酒","无酒精"],favoriteDrink:"Espresso Martini",drinkAbv:20,meetScene:"匹配女生闻出杯里的烘焙香，笑着和你比较咖啡与酒的苦味。"},
  {id:"F11",gender:"woman",age:27,city:"重庆",height:173,role:"舞蹈老师",vibe:"spark",musicStyles:["Latin House","Dance Pop"],musicEnergy:5,favoriteTrack:"DANCE...",drinkFamilies:["起泡果味","低度开胃"],favoriteDrink:"Aperol Spritz",drinkAbv:9,meetScene:"匹配女生在舞圈边先示意是否愿意加入，手始终停在安全距离。"},
  {id:"F12",gender:"woman",age:26,city:"苏州",height:169,role:"古籍修复师",vibe:"mystery",musicStyles:["Indie Folk","Dream Pop"],musicEnergy:2,favoriteTrack:"Doors",drinkFamilies:["清酒","自然葡萄酒"],favoriteDrink:"Junmai Sake",drinkAbv:15,meetScene:"匹配女生注意到杯垫上的印刷纹理，从纸张聊到各自最近读的书。"},
  {id:"F13",gender:"woman",age:31,city:"天津",height:176,role:"建筑策展人",vibe:"mystery",musicStyles:["House","Nu-Disco"],musicEnergy:4,favoriteTrack:"New Religion",drinkFamilies:["苦甜经典","现代苦甜"],favoriteDrink:"Negroni",drinkAbv:24,meetScene:"匹配女生从空间动线聊到 DJ 台的位置，邀请你交换对这家店的第一印象。"},
  {id:"F14",gender:"woman",age:24,city:"青岛",height:164,role:"海洋研究助理",vibe:"chill",musicStyles:["Indie Pop","Folk Pop"],musicEnergy:2,favoriteTrack:"Boston",drinkFamilies:["淡色拉格","无酒精"],favoriteDrink:"Lager",drinkAbv:5,meetScene:"匹配女生端着一杯拉格看窗外，问你海边城市的夜和这里有什么不同。"},
  {id:"F15",gender:"woman",age:29,city:"西安",height:170,role:"博物馆教育员",vibe:"mystery",musicStyles:["华语 Indie Rock","Mandopop"],musicEnergy:3,favoriteTrack:"爱人错过",drinkFamilies:["中国白酒","日式长饮"],favoriteDrink:"Highball",drinkAbv:10,meetScene:"匹配女生认出歌里的历史采样，把一个知识点讲得像好玩的故事。"},
  {id:"F16",gender:"woman",age:27,city:"昆明",height:168,role:"植物研究员",vibe:"chill",musicStyles:["Neo-Soul","City Pop"],musicEnergy:2,favoriteTrack:"Earrings",drinkFamilies:["草本短饮","无酒精"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,meetScene:"匹配女生正在辨认酒里的植物香气，邀请你一起猜是罗勒还是柑橘叶。"},
  {id:"F17",gender:"woman",age:25,city:"佛山",height:162,role:"陶艺师",vibe:"chill",musicStyles:["Mandopop","Neo-Soul"],musicEnergy:2,favoriteTrack:"红色高跟鞋",drinkFamilies:["清酒","起泡果味"],favoriteDrink:"Bellini",drinkAbv:8,meetScene:"匹配女生先注意到酒杯的手工质感，再问你会不会因为杯子改变对酒的判断。"},
  {id:"F18",gender:"woman",age:28,city:"珠海",height:174,role:"帆船教练",vibe:"spark",musicStyles:["Global Pop","Afrobeats"],musicEnergy:5,favoriteTrack:"Dai Dai",drinkFamilies:["朗姆长饮","清爽长饮"],favoriteDrink:"Mojito",drinkAbv:13,meetScene:"匹配女生刚从露台回来，扶住门后问你要不要一起去有风的地方聊。"},
  {id:"F19",gender:"woman",age:32,city:"宁波",height:172,role:"供应链顾问",vibe:"mystery",musicStyles:["French House","Disco House"],musicEnergy:4,favoriteTrack:"Get Lucky",drinkFamilies:["起泡鸡尾酒","低度开胃"],favoriteDrink:"French 75",drinkAbv:15,meetScene:"匹配女生准确说出一段 Disco 采样，却没有把谈话变成知识竞赛。"},
  {id:"F20",gender:"woman",age:26,city:"无锡",height:166,role:"游戏编剧",vibe:"spark",musicStyles:["Synthpop","Electropop"],musicEnergy:4,favoriteTrack:"Self Aware",drinkFamilies:["花香经典","莓果酸酒"],favoriteDrink:"Aviation",drinkAbv:22,meetScene:"匹配女生把酒单当作角色设定读，问你会给今晚的自己什么隐藏任务。"},
  {id:"F21",gender:"woman",age:30,city:"合肥",height:175,role:"机器人产品经理",vibe:"mystery",musicStyles:["Electroclash","Indietronica"],musicEnergy:4,favoriteTrack:"L.U.C.K.Y",drinkFamilies:["烈酒短饮","无酒精"],favoriteDrink:"Dry Martini",drinkAbv:29,meetScene:"匹配女生从机械节拍聊到人为什么会在舞池里放松警惕。"},
  {id:"F22",gender:"woman",age:23,city:"福州",height:161,role:"甜品师",vibe:"spark",musicStyles:["Disco Pop","K-Pop Crossover"],musicEnergy:5,favoriteTrack:"Espresso",drinkFamilies:["咖啡鸡尾酒","热带奶油"],favoriteDrink:"Espresso Martini",drinkAbv:20,meetScene:"匹配女生把杯中甜味拆成三层，问你最像甜点的一杯酒是哪种。"},
  {id:"F23",gender:"woman",age:29,city:"郑州",height:170,role:"纪录片制片人",vibe:"chill",musicStyles:["Americana","Heartland Rock"],musicEnergy:3,favoriteTrack:"Kingdom of Fear",drinkFamilies:["精酿啤酒","威士忌酸酒"],favoriteDrink:"IPA",drinkAbv:6,meetScene:"匹配女生听见你谈到家乡，问的不是哪里好玩，而是什么声音最让你想起那里。"},
  {id:"F24",gender:"woman",age:27,city:"沈阳",height:177,role:"现场灯光师",vibe:"spark",musicStyles:["EDM","Progressive House"],musicEnergy:5,favoriteTrack:"Levels",drinkFamilies:["无酒精","低度开胃"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,meetScene:"匹配女生预判到下一次灯光变化，笑着让你注意副歌落下的那一秒。"},
  {id:"M07",gender:"man",age:25,city:"杭州",height:179,role:"交互设计师",vibe:"mystery",musicStyles:["Indietronica","Synthpop"],musicEnergy:3,favoriteTrack:"Midnight City",drinkFamilies:["日式长饮","无酒精"],favoriteDrink:"Highball",drinkAbv:10,meetScene:"匹配男生在互动装置前研究了很久，转身问你觉得它是在回应人还是诱导人。"},
  {id:"M08",gender:"man",age:31,city:"南京",height:184,role:"高校讲师",vibe:"chill",musicStyles:["Neo-Soul","Indie Folk"],musicEnergy:2,favoriteTrack:"Doors",drinkFamilies:["自然葡萄酒","纯饮烈酒"],favoriteDrink:"Natural Red Wine",drinkAbv:13,meetScene:"匹配男生没有急着解释酒，只问你第一口最先注意到什么。"},
  {id:"M09",gender:"man",age:27,city:"武汉",height:181,role:"音乐制作人",vibe:"spark",musicStyles:["Hip-Hop","华语 Hip-Hop"],musicEnergy:5,favoriteTrack:"大展鸿图",drinkFamilies:["咸鲜鸡尾酒","日式长饮"],favoriteDrink:"Highball",drinkAbv:10,meetScene:"匹配男生听见你认出鼓点切分，先问你想聊歌词还是制作。"},
  {id:"M10",gender:"man",age:24,city:"厦门",height:175,role:"冲浪教练",vibe:"spark",musicStyles:["Afropop","Global Pop"],musicEnergy:5,favoriteTrack:"Dai Dai",drinkFamilies:["朗姆长饮","龙舌兰长饮"],favoriteDrink:"Paloma",drinkAbv:12,meetScene:"匹配男生从露台风向聊到海浪节奏，话题轻松但没有擅自靠近。"},
  {id:"M11",gender:"man",age:29,city:"重庆",height:186,role:"餐厅主厨",vibe:"mystery",musicStyles:["Alternative R&B","Neo-Soul"],musicEnergy:2,favoriteTrack:"NOBLE",drinkFamilies:["咸鲜鸡尾酒","苦甜经典"],favoriteDrink:"Negroni",drinkAbv:24,meetScene:"匹配男生从一杯酒里的盐味聊到食物记忆，认真听你说完才回应。"},
  {id:"M12",gender:"man",age:26,city:"苏州",height:177,role:"园林设计师",vibe:"chill",musicStyles:["Dream Pop","City Pop"],musicEnergy:2,favoriteTrack:"Plastic Love",drinkFamilies:["清酒","无酒精"],favoriteDrink:"Junmai Sake",drinkAbv:15,meetScene:"匹配男生说这家店最舒服的是一块留白，问你通常怎样判断空间是否安全。"},
  {id:"M13",gender:"man",age:32,city:"天津",height:183,role:"工业设计师",vibe:"mystery",musicStyles:["Tech House","House"],musicEnergy:4,favoriteTrack:"Free Your Mind",drinkFamilies:["威士忌经典","现代苦甜"],favoriteDrink:"Old Fashioned",drinkAbv:28,meetScene:"匹配男生观察透明冰融化的速度，顺势问你更在乎味道还是仪式感。"},
  {id:"M14",gender:"man",age:23,city:"青岛",height:180,role:"精酿酒吧店员",vibe:"spark",musicStyles:["Pop Rock","Indie Rock"],musicEnergy:4,favoriteTrack:"drop dead",drinkFamilies:["精酿啤酒","黑啤"],favoriteDrink:"IPA",drinkAbv:6,meetScene:"匹配男生只描述啤酒花像柚子皮，没有假设你必须懂任何专业词。"},
  {id:"M15",gender:"man",age:28,city:"西安",height:176,role:"考古绘图师",vibe:"chill",musicStyles:["华语 Indie Rock","Folk Pop"],musicEnergy:3,favoriteTrack:"爱人错过",drinkFamilies:["中国白酒","无酒精"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,meetScene:"匹配男生从杯垫图案聊到城市旧墙，问题具体又不过度私人。"},
  {id:"M16",gender:"man",age:30,city:"昆明",height:182,role:"野生动物摄影师",vibe:"mystery",musicStyles:["Indie Folk","Americana"],musicEnergy:2,favoriteTrack:"Mexico Honey",drinkFamilies:["自然葡萄酒","精酿啤酒"],favoriteDrink:"Natural Red Wine",drinkAbv:13,meetScene:"匹配男生把相机完全收进包里后才加入谈话，避免镜头造成压力。"},
  {id:"M17",gender:"man",age:26,city:"佛山",height:174,role:"家具设计师",vibe:"chill",musicStyles:["French House","Nu-Disco"],musicEnergy:4,favoriteTrack:"Get Lucky",drinkFamilies:["低度开胃","起泡果味"],favoriteDrink:"Aperol Spritz",drinkAbv:9,meetScene:"匹配男生让出靠背更舒服的位置，没有把体贴变成交换条件。"},
  {id:"M18",gender:"man",age:29,city:"珠海",height:188,role:"航空工程师",vibe:"mystery",musicStyles:["Synthwave","Progressive House"],musicEnergy:4,favoriteTrack:"Midnight City",drinkFamilies:["烈酒短饮","日式长饮"],favoriteDrink:"Dry Martini",drinkAbv:29,meetScene:"匹配男生从夜航灯光聊到这家店的色温，等你回应后才继续问题。"},
  {id:"M19",gender:"man",age:25,city:"宁波",height:178,role:"服装买手",vibe:"spark",musicStyles:["K-Pop Crossover","Disco Pop"],musicEnergy:5,favoriteTrack:"APT.",drinkFamilies:["起泡果味","无酒精"],favoriteDrink:"Bellini",drinkAbv:8,meetScene:"匹配男生只赞美你选择的配色，没有评价身体或追问品牌。"},
  {id:"M20",gender:"man",age:33,city:"无锡",height:185,role:"麻醉科医生",vibe:"chill",musicStyles:["Neo-Soul","Alternative R&B"],musicEnergy:2,favoriteTrack:"Earrings",drinkFamilies:["无酒精","日式长饮"],favoriteDrink:"Zero-proof Tonic",drinkAbv:0,meetScene:"匹配男生整晚选择无酒精饮品，也不询问别人为什么喝或不喝。"},
  {id:"M21",gender:"man",age:27,city:"合肥",height:181,role:"算法工程师",vibe:"mystery",musicStyles:["Electropop","Tech House"],musicEnergy:4,favoriteTrack:"Self Aware",drinkFamilies:["苦甜经典","咖啡鸡尾酒"],favoriteDrink:"Negroni",drinkAbv:24,meetScene:"匹配男生把随机歌单比作推荐系统，随后认真问你不想被算法猜中的部分。"},
  {id:"M22",gender:"man",age:24,city:"福州",height:173,role:"独立漫画作者",vibe:"spark",musicStyles:["Power Pop","Pop Rock"],musicEnergy:4,favoriteTrack:"hate that i made you love me",drinkFamilies:["莓果酸酒","清爽长饮"],favoriteDrink:"Clover Club",drinkAbv:18,meetScene:"匹配男生在杯垫上画了一个表情，问你愿不愿意替它写一句台词。"},
  {id:"M23",gender:"man",age:30,city:"郑州",height:179,role:"铁路工程师",vibe:"chill",musicStyles:["Heartland Rock","Country Pop"],musicEnergy:3,favoriteTrack:"Choosin’ Texas",drinkFamilies:["威士忌酸酒","淡色拉格"],favoriteDrink:"Whiskey Sour",drinkAbv:19,meetScene:"匹配男生从末班车时间聊到最喜欢的一段铁路风景，不催促你留下。"},
  {id:"M24",gender:"man",age:28,city:"沈阳",height:187,role:"冰球教练",vibe:"spark",musicStyles:["EDM","Dance Pop"],musicEnergy:5,favoriteTrack:"Bangaranga",drinkFamilies:["无酒精","姜味长饮"],favoriteDrink:"Moscow Mule",drinkAbv:11,meetScene:"匹配男生邀请你加入舞池前先问是否喜欢高能量音乐，拒绝也不会继续劝。"},
];

const PROFILE_FACES = ["椭圆脸、杏眼、平直眉、柔和鼻梁、均衡唇形","圆脸、内双眼、自然弯眉、圆润鼻尖、微笑唇","偏方脸、细长眼、浓直眉、直鼻、偏薄唇形","心形脸、上扬眼、挑眉、小巧鼻尖、饱满下唇","偏长脸、深眼窝、平眉、立体鼻梁、唇峰清晰","鹅蛋脸、圆眼、自然眉、柔和鼻梁、均衡唇形"];
const PROFILE_HAIRS = ["利落短发","齐耳短发","锁骨直发","自然卷中发","低马尾","短碎发"];
const PROFILE_OUTFITS = ["极简黑白与银色配饰","复古夹克与直筒裤","利落西装与素色内搭","柔软针织与低饱和配色","城市街头廓形与运动鞋","深色衬衫与干净皮鞋"];
const CONVERSATION_BY_VIBE: Record<MatchProfile["vibe"],string> = {spark:"回应速度快，擅长用具体玩笑和共同活动建立气氛，但会观察对方是否接得住。",mystery:"先听后问，习惯从一个具体细节慢慢进入更深话题，不会连续追问隐私。",chill:"允许沉默和停顿，重视让双方舒服，不靠夸张故事制造熟悉感。"};
const BOUNDARIES = ["不劝酒；任何身体接触前都会确认。","不接受未经同意的拍照或公开发布。","偏好先在公共场所交流，回程各自确认安全。","拒绝会被立即接受，不追问理由。","亲密决定只在双方清醒时讨论。","愿意交换轻量联系方式，不要求即时回复。"];

export const MATCH_PROFILES: MatchProfile[] = [
  ...BASE_MATCH_PROFILES,
  ...EXTRA_PROFILE_SEEDS.map((seed,index)=>({
    ...seed,
    face:PROFILE_FACES[index%PROFILE_FACES.length],
    hair:PROFILE_HAIRS[(index*2)%PROFILE_HAIRS.length],
    outfit:PROFILE_OUTFITS[(index*3)%PROFILE_OUTFITS.length],
    conversation:CONVERSATION_BY_VIBE[seed.vibe],
    boundary:BOUNDARIES[index%BOUNDARIES.length],
  })),
];

const MUSIC_DESCRIPTIONS: Record<string, string> = {
  "House":"诞生于芝加哥俱乐部文化，核心是稳定的四拍踩镲、反复低音和合成器。它像一条不断向前的传送带，很适合不想研究舞步、只想跟着节奏进入状态的人。",
  "Disco House":"把 House 的四拍骨架与 Disco 的弦乐、放克贝斯、女声切片结合。听感闪亮又复古，适合刚认识的人一起轻松跳舞，不必一开始就把气氛推到最硬。",
  "Electroclash":"把合成器流行、Electro、New Wave 与朋克式态度混在一起，故意保留冰冷机器感和一点戏谑。适合穿搭大胆、喜欢锐利节拍和千禧年代夜店美学的玩家。",
  "Amapiano":"源自南非的舞曲风格，常见温暖钢琴和弦、沙锤细节、深沉低音与标志性的 Log Drum。节奏看似松弛，低频却会慢慢接管身体，适合长时间摇摆而不是短暂爆发。",
  "Alternative Rock":"广义上来自主流摇滚之外的独立与地下传统，吉他、鼓和个人化表达通常比标准流行公式更重要。它适合想保留一点棱角，又不排斥旋律与现场感的人。",
  "Indie Pop":"强调轻盈旋律、亲密写作和独立制作气质，常把吉他、合成器或卧室录音的质感混在一起。它不一定安静，却通常比大制作流行更像朋友分享的一首私藏。",
  "Country Pop":"把乡村音乐的叙事、木吉他或口音元素，与流行音乐清晰的副歌和制作结合。适合喜欢歌词故事、容易跟唱，又不想整晚都泡在重低音里的人。",
  "Dance Pop":"以明确副歌、稳定节拍和舞池可用性为目标的流行音乐。结构通常直给、记忆点来得快，是聚会里最容易让不同音乐背景的人同时进入状态的安全选择。",
  "Afrobeats":"当代西非流行音乐的重要类型，常融合 Highlife、Hip-Hop、Dancehall 与电子制作；注意它不同于 Fela Kuti 时代的 Afrobeat。节奏富有弹性，适合边聊天边自然摆动。",
  "Hip-Hop":"以节拍、押韵、Flow、采样与 DJ 文化为核心，从纽约街区文化发展成全球语言。选择它往往意味着你在意节奏和表达，适合从歌词、制作人或地域风格开始聊天。",
  "Pop Rock":"把流行音乐易记的旋律和摇滚乐队的吉他鼓组结合，通常比硬摇滚明亮、比纯流行更有现场冲击。适合想跟唱、挥手，也想感受真鼓与失真吉他的玩家。",
  "Psychedelic Pop":"借用迷幻摇滚的空间效果、循环、相位和超现实音色，但保留流行歌的旋律与篇幅。听感像灯光被拉出残影，适合喜欢层次、氛围和一点不真实感的人。",
  "Latin House":"用 House 的四拍节奏承载拉丁打击乐、号角、声乐或热带采样。它比标准 House 更外放、更有身体律动，适合快速打破拘谨，但不代表必须会任何特定舞种。",
  "Latin Afrobeats":"把拉丁流行、加勒比节奏与 Afrobeats 的弹性鼓点相连，是一种跨地区的当代融合。它的乐趣在于重拍不笨重、旋律又容易记，适合多语言和热闹社交场景。",
  "Neo-Soul":"在当代 R&B 基础上更强调经典 Soul 的和声、乐手感和松弛 Groove。人声通常有呼吸与细节，适合坐席酒吧、慢慢聊天，以及愿意认真听完一段演唱的人。",
  "Folk Pop":"用民谣的原声乐器和叙事感，搭配流行音乐简洁、好记的结构。它不靠巨大低频抢注意力，适合分享歌词、旅行与个人故事的夜晚。",
  "Power Pop":"以响亮吉他、紧凑节奏和极强副歌为标志，继承 1960 年代流行旋律与摇滚冲劲。听起来阳光直接，却常藏着失恋歌词，适合边跳边大声合唱。",
  "Americana":"从美国民谣、乡村、蓝草、布鲁斯和 Roots Rock 汲取声音，更像一个文化集合而非单一节拍公式。适合喜欢木质音色、公路感和人物叙事的人。",
  "Alté":"源自尼日利亚青年文化的“Alternative”取向，常自由混合 Afrobeats、R&B、Rap、Indie 与时尚视觉。它不追求统一模板，适合喜欢新鲜审美和跨风格歌单的人。",
  "Electropop":"以合成器、电子鼓和精炼流行旋律为核心，声音通常比传统乐队更明亮、规整。适合喜欢未来感、干净低频和强副歌，但又不想进入纯地下电子场景的人。",
  "Country":"重视人物、地点和日常生活的叙事，常见木吉他、钢棒吉他、班卓或小提琴。即使不熟悉乡村文化，也可以从歌词里的具体故事进入。",
  "Afropop":"泛指非洲各地面向当代大众市场的流行音乐，可能融合本地语言、传统节奏、电子制作与全球流行元素。范围很广，适合对地域声音和旋律变化有好奇心的人。",
  "Indie Folk":"把民谣的原声质感与独立音乐更私人、实验或低保真的表达结合。它适合音量稍低的空间，让陌生人不必喊话，也更容易聊到歌词背后的情绪。",
  "Reggaeton":"起源与波多黎各、巴拿马等拉丁加勒比文化密切相关，标志是持续的 Dembow 节奏。它直接、循环而有身体感，适合舞池升温，但不等于所有拉丁音乐。",
  "UK Garage":"英国 1990 年代发展的电子舞曲，常见切分鼓点、摇摆节奏、低音和经过切片的人声。比四拍 House 更跳跃，适合喜欢脚步变化和俏皮律动的人。",
  "Tech House":"把 Techno 的简洁机械质感与 House 的 Groove 结合，通常依靠低音、鼓组和细小变化推进。它不急着给大副歌，适合真正想连续跳一段时间的人。",
  "Heartland Rock":"以朴实摇滚编制、普通人的生活叙事和宽阔副歌著称，常带公路与小镇想象。适合喜欢真实乐队感、愿意跟着歌词建立情绪的人。",
  "Synthpop":"以合成器作为主要旋律与质感来源，兴起于 1970 年代末至 1980 年代，并延续至今。它可以冷峻也可以浪漫，适合霓虹灯、复古未来感和清晰节拍。",
  "Europop":"泛指欧洲制作传统中明亮、旋律突出、面向大众舞池的流行音乐。副歌通常简单有力，适合语言不同的人一起唱，也常带一点节庆式夸张。",
  "Global Pop":"不是严格的单一流派，而是把不同地区的语言、节奏和流行制作放在同一首歌中。适合世界性活动和大范围社交场景，优点是进入门槛低、文化线索多。",
  "华语 Hip-Hop":"用普通话、方言或多语 Flow 连接现代 Beat、采样和本地叙事。它既有派对型作品，也有很具体的城市经验，适合从押韵、地域和歌词梗开启话题。",
  "K-Pop Crossover":"以韩国流行工业的精密制作为基础，常跨入 Rock、Hip-Hop、EDM 或英语流行市场。编曲段落变化快、记忆点密集，适合喜欢舞蹈、视觉和多人合唱的人。",
  "Pop Ballad":"把人声、歌词和缓慢情绪推进放在中心，常用钢琴、弦乐或逐步扩大的鼓组制造高潮。适合暂时离开舞池、认真听一句歌词，也适合深夜收尾。",
  "Dream Pop":"一种重视音色纹理的氛围型另类流行，常见气声、混响吉他与漂浮合成器。它像给现实罩上柔焦，适合慢热、想保持距离又享受情绪的人。",
  "Disco Pop":"把 Disco 的弹性贝斯、四拍节奏和华丽弦乐，压缩进现代流行歌的清晰结构。它复古但不古板，适合第一次见面时用熟悉律动减轻尴尬。",
  "Synthwave":"受 1980 年代电影配乐、街机与模拟合成器想象影响的复古电子风格。常有脉冲低音和夜间驾驶感，适合想把城市夜景变成电影片头的人。",
  "Nu-Disco":"21 世纪对 Disco 与 Boogie 的现代复兴，通常保留放克贝斯和闪亮和弦，同时使用更干净的电子制作。适合优雅地热场，不必一上来就进入高强度音乐。",
  "Dance / Electronic":"覆盖范围很广，指以电子制作和舞蹈节拍为核心、但不局限于单一地下流派的作品。它适合不想背风格名词，只想选一首能动起来的歌。",
  "EDM":"Electronic Dance Music 的大众化统称，常指大型节庆中使用明显 Build-up 与 Drop 的电子舞曲。高潮来得清楚，适合集体释放，但连续聆听的强度也较高。",
  "Progressive House":"通过层层叠加的旋律、和弦与鼓组缓慢建立高潮，重视长线推进而非频繁切换。适合从热场逐步走向大合唱，让情绪像坡道一样上升。",
  "Indietronica":"把独立摇滚或独立流行的写作，与电子鼓、采样、合成器和电脑制作结合。它兼有人的脆弱感与机器纹理，适合喜欢小众旋律又不排斥电子声音的人。",
  "French House":"法国 1990 年代兴起的 House 分支，常使用 Disco/Funk 采样、滤波扫频和压缩感强的循环。声音像镜面反光，适合复古、时髦而持续的舞池。",
  "Alternative R&B":"在 R&B 人声与节奏基础上加入电子、Indie、Ambient 或更非传统的歌曲结构。它通常更私密、夜色更深，适合暧昧但不喧闹的交流。",
  "Amapiano Pop":"把 Amapiano 的钢琴、Log Drum 和南非律动压缩进更短、更好记的流行结构。既保留低频摇摆又容易跟唱，适合从歌单模式顺滑进入舞池。",
  "Afrobeat Pop":"把西非节奏传统、铜管或律动意识与当代流行结构结合；名称常与 Afrobeats 混用，但历史来源并不完全相同。这里更强调跨界旋律和轻快社交感。",
  "Reggaeton Pop":"保留 Reggaeton 的 Dembow 鼓点，同时使用更明显的流行副歌、抒情段落和跨语种制作。适合初次接触拉丁节奏的人，熟悉度比地下版本更高。",
  "Funk Pop":"以切分节奏、弹性贝斯、吉他短句和明亮铜管为流行歌曲增加 Groove。它的快乐很具体，适合全场一起拍手、互动和做不太严肃的舞步。",
  "Mandopop":"以普通话演唱的华语流行音乐，覆盖抒情、电子、摇滚和 R&B 等多种制作。共同语言和熟悉歌词会降低交流门槛，很适合点歌与合唱场景。",
  "华语 Indie Rock":"来自华语独立乐队与现场文化，常以吉他编制、个人写作和城市经验区别于标准工业流行。适合从演出、城市和歌词里的细节建立真实话题。",
  "City Pop":"与日本 1970 年代末至 1980 年代都市消费文化密切相关，常融合 Funk、Disco、Soft Rock 和 Jazz。它有夜间公路、霓虹与夏日感，适合轻松但讲究质感的酒吧。",
};

const search = (title: string, artist: string) => `${title} ${artist}`;
const MUSIC_BASE = [
  { title:"New Religion",artist:"Bebe Rexha, Faithless",style:"House",energy:4,id:"2Lb9ww5vZAnveWnrFQfAKR" },
  { title:"Talk To You",artist:"ANOTR, 54 Ultra",style:"Disco House",energy:4,id:"0kl6Ozan3fuUdCl6TlB15v" },
  { title:"DANCE...",artist:"Slayyyter",style:"Electroclash",energy:5,id:"5rfOARz6QO73wPATyMtQQZ" },
  { title:"Kakalika",artist:"DopeNation",style:"Amapiano",energy:5,id:"1p5F0slR5AF49EDX5o125x" },
  { title:"Freakin’ Out",artist:"Dexter and The Moonrocks",style:"Alternative Rock",energy:3,id:"2SaWT781xr3hHLdbVt5DB7" },
  { title:"Babydoll",artist:"Dominic Fike",style:"Indie Pop",energy:2,id:"7yNf9YjeO5JXUE3JEBgnYc" },
  { title:"Choosin’ Texas",artist:"Ella Langley",style:"Country Pop",energy:3,id:"7scFxt9VhL4FJwuPSfRlfN" },
  { title:"Bangaranga",artist:"DARA",style:"Dance Pop",energy:5,id:"6SvlfrQYzUsW5UQUpUpy26" },
  { title:"Raindance",artist:"Dave, Tems",style:"Afrobeats",energy:4,id:"3oTuTpF1F3A7rEC6RKsMRz" },
  { title:"Janice STFU",artist:"Drake",style:"Hip-Hop",energy:4,id:"514joG57v4yKTsfQmz7stz" },
  { title:"drop dead",artist:"Olivia Rodrigo",style:"Pop Rock",energy:4,id:"6gkbtMtioHgtyGjrMel6ei" },
  { title:"Dracula · JENNIE Remix",artist:"Tame Impala, JENNIE",style:"Psychedelic Pop",energy:4,id:"5yvVYFDUpbnjcnRBgjwTzM" },
  { title:"Jamaican (Bam Bam)",artist:"HUGEL, SOLTO",style:"Latin House",energy:5,id:"7e4zDInS6tA2jwzphvs2Ay" },
  { title:"CHÉVERE",artist:"ARIA VEGA, Ryan Castro",style:"Latin Afrobeats",energy:5,id:"3CBEVPwR3kUXDoTx1lqFUQ" },
  { title:"Earrings",artist:"Malcolm Todd",style:"Neo-Soul",energy:2,id:"0eAuGrXyGFYwur9ARUe7LJ" },
  { title:"Boston",artist:"STELLA LEFTY",style:"Folk Pop",energy:2,id:"36idurZmYRjJ56KQ8JD9bN" },
  { title:"hate that i made you love me",artist:"Ariana Grande",style:"Power Pop",energy:4,id:"20jbSiX29FDX4oQxBXyUEi" },
  { title:"Kingdom of Fear",artist:"Cameron Whitcomb",style:"Americana",energy:3,id:"4Es6f0zquGHCrv9Hespx9W" },
  { title:"NOBLE",artist:"F3miii",style:"Alté",energy:4,id:"2LSmH4vxyRhkJ2pPqcmkXw" },
  { title:"L.U.C.K.Y",artist:"Fcukers",style:"Electropop",energy:5,id:"1KoTSKG0vs2vbzMvrbpWjp" },
  { title:"Mexico Honey",artist:"Kacey Musgraves",style:"Country",energy:2,id:"7xKr077iMufVJwge6aO9xJ" },
  { title:"Maladie",artist:"Mauvais djo",style:"Afropop",energy:4,id:"4zPb5wNcdTy15BgBvRVNYM" },
  { title:"Doors",artist:"Noah Kahan",style:"Indie Folk",energy:2,id:"3iU2qsthCTo5EeTE03l3Si" },
  { title:"KOKO",artist:"Omar Courtz",style:"Reggaeton",energy:5,id:"1tz7RZirwiuaJw2p0jbdHb" },
  { title:"Girl Like Me",artist:"PinkPantheress",style:"UK Garage",energy:4,id:"7aYGCP34Xo6XujY7Ix1DxB" },
  { title:"Free Your Mind",artist:"Prospa, Cloonee",style:"Tech House",energy:5,id:"6TWbY1dq8eYtFiMiGdBlOa" },
  { title:"Rein Me In",artist:"Sam Fender, Olivia Dean",style:"Heartland Rock",energy:3,id:"7MZHqgTVTnN6xZGYAcEEAf" },
  { title:"Self Aware",artist:"Temper City",style:"Synthpop",energy:4,id:"4qW3BbQAwZsrnu8a3ZRdyT" },
  { title:"Midnight Sun",artist:"Zara Larsson",style:"Europop",energy:5,id:"7N1GSHGlLwXY3lN5gv3QLV" },
  { title:"Dai Dai",artist:"Shakira, Burna Boy",style:"Global Pop",energy:5,id:"4TSStAtQq6HWYwa46elQCS" },
  { title:"大展鸿图",artist:"揽佬SKAI ISYOURGOD, AR刘夫阳",style:"华语 Hip-Hop",energy:5,id:"0hEWvzkgbI301JZj947gFz" },
  { title:"APT.",artist:"ROSÉ, Bruno Mars",style:"K-Pop Crossover",energy:5,query:search("APT.","ROSÉ Bruno Mars") },
  { title:"Die With A Smile",artist:"Lady Gaga, Bruno Mars",style:"Pop Ballad",energy:2,query:search("Die With A Smile","Lady Gaga Bruno Mars") },
  { title:"BIRDS OF A FEATHER",artist:"Billie Eilish",style:"Dream Pop",energy:2,query:search("BIRDS OF A FEATHER","Billie Eilish") },
  { title:"Espresso",artist:"Sabrina Carpenter",style:"Disco Pop",energy:4,query:search("Espresso","Sabrina Carpenter") },
  { title:"Blinding Lights",artist:"The Weeknd",style:"Synthwave",energy:5,query:search("Blinding Lights","The Weeknd") },
  { title:"Levitating",artist:"Dua Lipa",style:"Nu-Disco",energy:5,query:search("Levitating","Dua Lipa") },
  { title:"One Kiss",artist:"Calvin Harris, Dua Lipa",style:"Dance / Electronic",energy:5,query:search("One Kiss","Calvin Harris Dua Lipa") },
  { title:"Titanium",artist:"David Guetta, Sia",style:"EDM",energy:5,query:search("Titanium","David Guetta Sia") },
  { title:"Levels",artist:"Avicii",style:"Progressive House",energy:5,query:search("Levels","Avicii") },
  { title:"Midnight City",artist:"M83",style:"Indietronica",energy:4,query:search("Midnight City","M83") },
  { title:"Get Lucky",artist:"Daft Punk, Pharrell Williams",style:"French House",energy:4,query:search("Get Lucky","Daft Punk") },
  { title:"Starboy",artist:"The Weeknd, Daft Punk",style:"Alternative R&B",energy:4,query:search("Starboy","The Weeknd Daft Punk") },
  { title:"Water",artist:"Tyla",style:"Amapiano Pop",energy:4,query:search("Water","Tyla") },
  { title:"Calm Down",artist:"Rema, Selena Gomez",style:"Afrobeat Pop",energy:3,query:search("Calm Down","Rema Selena Gomez") },
  { title:"Despacito",artist:"Luis Fonsi, Daddy Yankee",style:"Reggaeton Pop",energy:5,query:search("Despacito","Luis Fonsi") },
  { title:"Uptown Funk",artist:"Mark Ronson, Bruno Mars",style:"Funk Pop",energy:5,query:search("Uptown Funk","Mark Ronson Bruno Mars") },
  { title:"红色高跟鞋",artist:"蔡健雅",style:"Mandopop",energy:3,query:search("红色高跟鞋","蔡健雅") },
  { title:"爱人错过",artist:"告五人",style:"华语 Indie Rock",energy:4,query:search("爱人错过","告五人") },
  { title:"Plastic Love",artist:"Mariya Takeuchi",style:"City Pop",energy:3,query:search("Plastic Love","Mariya Takeuchi") },
];

export const MUSIC: Music[] = MUSIC_BASE.map((item) => ({ ...item, description: MUSIC_DESCRIPTIONS[item.style] }));

const DRINK_DESCRIPTIONS: Record<string, string> = {
  "Negroni":"经典配方由金酒、甜味美思和 Campari 构成，通常等比例搅拌。入口先是橙皮与草本，随后出现明显苦甜；它适合慢慢喝，不适合把“苦”误认成酒坏了。",
  "Americano":"Campari 与甜味美思加苏打，是一杯带气泡的低度开胃酒，也常被视为 Negroni 家族的重要前身。苦橙、草本和气泡让它比烈酒短饮轻松，适合第一杯。",
  "Dry Martini":"以金酒和干味美思为核心，冰镇搅拌后用橄榄或柠檬皮点香。它不是甜味“马天尼”，而是一杯干燥、清冽、酒精存在感很高的经典短饮。",
  "Espresso Martini":"伏特加、咖啡利口酒与浓缩咖啡摇出细密泡沫，兼有烘焙苦香和甜味。它很适合想要甜点感的人，但咖啡因并不能抵消酒精或让人真正清醒。",
  "Cosmopolitan":"常用柑橘伏特加、橙味利口酒、蔓越莓与青柠，颜色醒目但核心是酸甜平衡。它比外表更干爽，适合喜欢莓果香、又不想喝成甜果汁的人。",
  "Margarita":"龙舌兰、橙味利口酒和青柠构成经典酸酒，杯口盐能放大柑橘与植物感。好喝的版本应有清楚酸度与龙舌兰味，不只是冰沙或糖浆。",
  "Paloma":"通常把龙舌兰与葡萄柚汽水或葡萄柚、青柠、苏打组合。它比 Margarita 更像清爽长饮，带果皮微苦和气泡，适合炎热天气与慢速社交。",
  "Mojito":"白朗姆、薄荷、青柠、糖和苏打组成的古巴长饮。薄荷应提供香气而不是被捣成苦叶碎，整体清爽、带气泡，适合第一次接触朗姆酒的人。",
  "Daiquiri":"真正的经典 Daiquiri 很简单：朗姆、青柠和糖，摇匀后滤入冰镇杯；它并不等于草莓冰沙。配方越简单，朗姆品质与酸甜平衡越容易被喝出来。",
  "Old Fashioned":"用威士忌、糖、苦精和少量水构成，是理解“烈酒主导型”鸡尾酒的好入口。冰块融化会逐渐打开香气，甜味只是修饰，不应盖住橡木和谷物。",
  "Manhattan":"常以黑麦或波本威士忌、甜味美思和苦精搅拌，带香料、草本与樱桃联想。它比 Old Fashioned 更圆润芳香，却仍是一杯酒精度较高的短饮。",
  "Whiskey Sour":"威士忌、柠檬与糖构成酸酒骨架，可加入蛋白形成绵密泡沫。酸度会让威士忌更易入口，但不会降低实际酒精量，适合喜欢柑橘与木质味的人。",
  "Highball":"把威士忌与大量冰、冰冷苏打轻轻结合，日式酒吧尤其重视温度、气泡和搅拌。它清爽、酒精度相对低，但精彩之处在于细腻而不是“威士忌兑水”。",
  "Boulevardier":"波本或黑麦、Campari 与甜味美思组成，可理解为威士忌版 Negroni。谷物与橡木让苦甜更厚、更温暖，适合天气偏冷或想慢慢结束一晚的时候。",
  "Aperol Spritz":"Aperol、Prosecco 和苏打构成意式开胃长饮，颜色鲜橙，常带橙皮、草本与轻微苦味。气泡活泼、酒精度不高，适合开场而不是追求烈度。",
  "French 75":"金酒、柠檬、糖与起泡酒结合，名字来自第一次世界大战时期法国 75 毫米野战炮的力量联想。它喝起来轻盈明亮，但气泡下藏着金酒，速度要慢。",
  "Tom Collins":"金酒、柠檬、糖和苏打装入高杯，是经典 Collins 长饮。它像更有结构的酒精柠檬汽水，清爽易懂，适合不熟悉草本型金酒的人。",
  "Gin Fizz":"金酒、柠檬、糖与苏打的 Fizz 家族成员，重点是摇和后产生的轻盈口感；部分版本会加入蛋白。与 Tom Collins 相近，但传统杯型和制作逻辑略有不同。",
  "Moscow Mule":"伏特加、姜汁啤酒和青柠组成，常用铜杯呈现；姜汁啤酒通常是无酒精的辛辣汽水。伏特加保持干净，姜的刺激和气泡才是主角。",
  "Bloody Mary":"伏特加与番茄汁为基础，常加入柠檬、伍斯特酱、辣椒、盐和胡椒。它更像咸鲜、辛香的液体料理，适合早午餐或喜欢番茄与香料的人。",
  "Pisco Sour":"南美葡萄蒸馏酒 Pisco 搭配柑橘、糖和蛋白，表面常滴苦精。口感兼具葡萄果香、酸度和奶油般泡沫，是秘鲁与智利都极具代表性的鸡尾酒。",
  "Caipirinha":"巴西经典以甘蔗蒸馏酒 Cachaça、青柠和糖直接在杯中制作。Cachaça 有青草、甘蔗与发酵感，青柠皮油带一点苦，风格比普通朗姆长饮更野生。",
  "Mai Tai":"经典 Tiki 配方以多种朗姆、青柠、橙味利口酒和杏仁糖浆 Orgeat 构成。它不是随意混合的热带果汁，优秀版本会同时展现朗姆层次、坚果香和清晰酸度。",
  "Piña Colada":"朗姆、椰子与菠萝构成波多黎各代表性热带饮品，常做成冰沙或摇和版本。口感奶油甜润，适合喜欢甜品感的人，但浓稠不等于酒精低。",
  "Cuba Libre":"朗姆、可乐和青柠看似简单，但青柠使它区别于普通 Rum & Coke。焦糖、香料、柑橘与气泡很容易理解，是认识朗姆长饮的友好入口。",
  "Long Island Iced Tea":"把伏特加、金酒、朗姆、龙舌兰、橙味利口酒、柑橘和可乐混合；名字里没有真正的茶。味道可能像冰茶，但烈酒种类多、实际强度高，应慢饮。",
  "Sidecar":"干邑或白兰地、橙味利口酒与柠檬组成的经典酸酒，常见糖边装饰。葡萄蒸馏酒的干果与橡木被柑橘提亮，风格优雅但并不轻。",
  "Sazerac":"新奥尔良经典，常用黑麦威士忌或干邑、糖、Peychaud’s 苦精，并以 Absinthe 涮杯。香气带茴香与香料，几乎没有果汁，是非常烈酒导向的选择。",
  "Mint Julep":"波本、薄荷、糖和大量碎冰组成，与美国肯塔基赛马会联系紧密。碎冰让杯壁结霜并逐步稀释威士忌，薄荷重在闻香，不宜被捣得发苦。",
  "Penicillin":"现代经典把调和苏格兰威士忌、柠檬、蜂蜜和姜结合，并常以泥煤威士忌漂浮增添烟熏。它同时有辛辣、酸甜和烟感，像一杯有火气的蜂蜜姜茶。",
  "Paper Plane":"等份波本、Aperol、Amaro Nonino 与柠檬构成的现代苦甜酸酒。颜色轻快，味道却包含柑橘、草本和威士忌，适合想尝苦味但怕 Negroni 太重的人。",
  "Aviation":"金酒、柠檬、Maraschino 樱桃利口酒和紫罗兰利口酒组成，淡紫色来自少量花香利口酒。它应是清爽酸酒带花香点缀，而不是香水般浓甜。",
  "Last Word":"经典上常将金酒、绿 Chartreuse、Maraschino 和青柠等份摇和。草本、甜、酸与酒精同时很强，却能彼此制衡，适合喜欢复杂药草香的人。",
  "Vesper":"因《皇家赌场》中的 James Bond 而知名，以金酒、伏特加和 Kina Lillet 的现代替代品构成。它比普通 Martini 更强、更直接，文化故事有趣，但绝不是轻松长饮。",
  "Clover Club":"金酒、覆盆子、柠檬和蛋白组成，得名于费城同名绅士俱乐部。莓果让颜色柔和，蛋白带来丝滑泡沫，但骨架仍是一杯清楚的金酒酸酒。",
  "Bellini":"源自威尼斯 Harry’s Bar，以白桃泥和 Prosecco 调制。它果香柔软、气泡轻盈，传统重点是成熟白桃而非人工桃味糖浆，适合早场或庆祝。",
  "Mimosa":"起泡酒与橙汁的经典早午餐组合，比例会因场合变化。它简单、果味直观，最好保持冰冷并避免过甜；轻松易喝也意味着容易不知不觉喝快。",
  "Pornstar Martini":"现代流行鸡尾酒，通常以香草伏特加、百香果和甜酸元素调制，旁边配一小杯起泡酒。百香果香强烈、甜点感明显，起泡酒通常分开啜饮而非必须倒入。",
  "Irish Coffee":"热咖啡、爱尔兰威士忌、糖与轻盈奶油组成，奶油漂浮在表面，饮用时咖啡穿过冷奶油。它兼具甜点与热饮感，但咖啡同样不会抵消酒精。",
  "Dark ’n’ Stormy":"以深色朗姆和姜汁啤酒组成，常加青柠；这个名称与 Goslings 商标传统有关。深色糖蜜、香料和姜的辛辣非常鲜明，适合喜欢强烈长饮的人。",
  "IPA":"India Pale Ale 的现代版本通常突出啤酒花香气与苦味，可出现柑橘、松针、热带水果或树脂感。不同地区差异很大，但总体比普通拉格更香、更苦、更有存在感。",
  "Lager":"使用低温发酵并经过熟成的啤酒大类，常见干净、清脆、麦芽与啤酒花平衡的风格。它不等于“淡而无味”，从轻型拉格到深色、强劲版本都存在。",
  "Stout":"以烘烤麦芽或大麦带来咖啡、可可、焦香和深色外观的艾尔啤酒。口感可能干爽也可能奶油甜润，颜色很深并不自动代表酒精度特别高。",
  "Champagne":"只有来自法国香槟区并符合法规的起泡酒才能称 Champagne，通常通过瓶中二次发酵获得气泡。除柑橘与苹果外，陈年还可能出现面包、坚果和酵母香。",
  "Natural Red Wine":"“自然酒”没有全球统一法律定义，通常指强调有机/低干预种植与酿造、较少添加的葡萄酒。风格可能清新多汁，也可能带浑浊或发酵感，不能仅凭标签判断品质。",
  "Junmai Sake":"Junmai 是只以米、米曲和水酿造、未添加酿造酒精的清酒类别。清酒通过米曲将淀粉转糖并同步发酵，工艺更接近复杂酿造，而不是简单的“米葡萄酒”。",
  "Baijiu":"中国白酒以高粱等谷物和酒曲发酵后蒸馏，存在酱香、浓香、清香等差异很大的香型。常见酒精度高，香气可能有水果、发酵粮、酱香或窖香，适合小杯品饮。",
  "Single Malt Whisky":"指在同一家蒸馏厂、以发芽大麦为原料生产的麦芽威士忌；它可以混合多个年份与橡木桶，并不等于“单桶”。常见麦芽、果干、香料、橡木或烟熏风味。",
  "Agave Spirit Flight":"把 Tequila、Mezcal 或其他龙舌兰蒸馏酒少量并排品尝，比较植物品种、产区、烹煮与蒸馏差异。并非所有 Mezcal 都强烈烟熏，重点是慢闻慢尝而不是连续 Shot。",
  "Zero-proof Tonic":"以无酒精植物蒸馏液、柑橘和汤力水构成，保留苦味、香气与气泡，却不加入酒精。适合想参与举杯和风味体验、同时保持完整判断力的人。",
};

const DRINK_BASE = [
  {name:"Negroni",base:"Gin · Vermouth · Campari",family:"苦甜经典",abv:24,mark:"N"},
  {name:"Americano",base:"Campari · Vermouth · Soda",family:"低度开胃",abv:12,mark:"A"},
  {name:"Dry Martini",base:"Gin · Dry Vermouth",family:"烈酒短饮",abv:29,mark:"M"},
  {name:"Espresso Martini",base:"Vodka · Coffee · Liqueur",family:"咖啡鸡尾酒",abv:20,mark:"E"},
  {name:"Cosmopolitan",base:"Vodka · Cranberry · Citrus",family:"果味短饮",abv:19,mark:"C"},
  {name:"Margarita",base:"Tequila · Lime · Triple Sec",family:"龙舌兰酸酒",abv:22,mark:"MG"},
  {name:"Paloma",base:"Tequila · Grapefruit · Soda",family:"龙舌兰长饮",abv:12,mark:"P"},
  {name:"Mojito",base:"Rum · Mint · Lime · Soda",family:"清爽长饮",abv:13,mark:"MJ"},
  {name:"Daiquiri",base:"Rum · Lime · Sugar",family:"朗姆酸酒",abv:21,mark:"D"},
  {name:"Old Fashioned",base:"Whiskey · Sugar · Bitters",family:"威士忌经典",abv:28,mark:"OF"},
  {name:"Manhattan",base:"Rye · Vermouth · Bitters",family:"威士忌短饮",abv:27,mark:"MH"},
  {name:"Whiskey Sour",base:"Whiskey · Lemon · Sugar",family:"酸酒",abv:19,mark:"WS"},
  {name:"Highball",base:"Whisky · Soda",family:"日式长饮",abv:10,mark:"HB"},
  {name:"Boulevardier",base:"Bourbon · Campari · Vermouth",family:"苦甜威士忌",abv:25,mark:"B"},
  {name:"Aperol Spritz",base:"Aperol · Prosecco · Soda",family:"意式开胃",abv:9,mark:"AS"},
  {name:"French 75",base:"Gin · Lemon · Sparkling",family:"起泡鸡尾酒",abv:15,mark:"75"},
  {name:"Tom Collins",base:"Gin · Lemon · Soda",family:"金酒长饮",abv:12,mark:"TC"},
  {name:"Gin Fizz",base:"Gin · Lemon · Soda",family:"Fizz",abv:13,mark:"GF"},
  {name:"Moscow Mule",base:"Vodka · Ginger Beer · Lime",family:"姜味长饮",abv:11,mark:"MM"},
  {name:"Bloody Mary",base:"Vodka · Tomato · Spice",family:"咸鲜鸡尾酒",abv:10,mark:"BM"},
  {name:"Pisco Sour",base:"Pisco · Lime · Egg White",family:"南美酸酒",abv:20,mark:"PS"},
  {name:"Caipirinha",base:"Cachaça · Lime · Sugar",family:"巴西经典",abv:22,mark:"CA"},
  {name:"Mai Tai",base:"Rum · Curaçao · Orgeat",family:"Tiki",abv:23,mark:"MT"},
  {name:"Piña Colada",base:"Rum · Coconut · Pineapple",family:"热带奶油",abv:13,mark:"PC"},
  {name:"Cuba Libre",base:"Rum · Cola · Lime",family:"朗姆长饮",abv:12,mark:"CL"},
  {name:"Long Island Iced Tea",base:"Five Spirits · Citrus · Cola",family:"高酒精长饮",abv:24,mark:"LI"},
  {name:"Sidecar",base:"Cognac · Triple Sec · Lemon",family:"白兰地酸酒",abv:24,mark:"SC"},
  {name:"Sazerac",base:"Cognac/Rye · Absinthe · Bitters",family:"新奥尔良经典",abv:32,mark:"SZ"},
  {name:"Mint Julep",base:"Bourbon · Mint · Sugar",family:"碎冰长饮",abv:22,mark:"MJ"},
  {name:"Penicillin",base:"Scotch · Lemon · Honey · Ginger",family:"现代经典",abv:20,mark:"PN"},
  {name:"Paper Plane",base:"Bourbon · Amaro · Aperol · Lemon",family:"现代苦甜",abv:19,mark:"PP"},
  {name:"Aviation",base:"Gin · Maraschino · Violet · Lemon",family:"花香经典",abv:22,mark:"AV"},
  {name:"Last Word",base:"Gin · Chartreuse · Maraschino · Lime",family:"草本短饮",abv:24,mark:"LW"},
  {name:"Vesper",base:"Gin · Vodka · Lillet",family:"高酒精 Martini",abv:31,mark:"V"},
  {name:"Clover Club",base:"Gin · Raspberry · Lemon · Egg White",family:"莓果酸酒",abv:18,mark:"CC"},
  {name:"Bellini",base:"Prosecco · Peach",family:"起泡果味",abv:8,mark:"BL"},
  {name:"Mimosa",base:"Sparkling Wine · Orange",family:"早午餐起泡",abv:7,mark:"MI"},
  {name:"Pornstar Martini",base:"Vodka · Passion Fruit · Sparkling",family:"热带现代经典",abv:17,mark:"PM"},
  {name:"Irish Coffee",base:"Irish Whiskey · Coffee · Cream",family:"热饮",abv:11,mark:"IC"},
  {name:"Dark ’n’ Stormy",base:"Dark Rum · Ginger Beer",family:"朗姆姜味",abv:13,mark:"DS"},
  {name:"IPA",base:"Hops · Malt · Yeast",family:"精酿啤酒",abv:6,mark:"IPA"},
  {name:"Lager",base:"Malt · Hops",family:"淡色拉格",abv:5,mark:"LG"},
  {name:"Stout",base:"Roasted Malt · Hops",family:"黑啤",abv:6,mark:"ST"},
  {name:"Champagne",base:"Traditional Method Sparkling Wine",family:"起泡酒",abv:12,mark:"CH"},
  {name:"Natural Red Wine",base:"Grapes · Wild Fermentation",family:"自然葡萄酒",abv:13,mark:"NW"},
  {name:"Junmai Sake",base:"Rice · Koji · Water",family:"清酒",abv:15,mark:"SA"},
  {name:"Baijiu",base:"Sorghum · Qu",family:"中国白酒",abv:42,mark:"白"},
  {name:"Single Malt Whisky",base:"Malted Barley · Oak",family:"纯饮烈酒",abv:43,mark:"SM"},
  {name:"Agave Spirit Flight",base:"Tequila · Mezcal",family:"龙舌兰品鉴",abv:40,mark:"AG"},
  {name:"Zero-proof Tonic",base:"Botanical · Citrus · Tonic",family:"无酒精",abv:0,mark:"0%"},
];

export const DRINKS: Drink[] = DRINK_BASE.map((item) => ({ ...item, description: DRINK_DESCRIPTIONS[item.name] }));

const P0 = [
  "FIRST LIGHT|雨水留在门外|你推开{bar}的门，伞尖滴下三滴水。寄存处的人递来号码牌，{track}的低频从地板升到锁骨，第一杯{drink}刚好在吧台亮起。",
  "WRONG DOOR|入口藏在意料之外|你绕过一扇没有招牌的门才找到{bar}。调酒师像认出老客一样点头，问你今晚想被热闹接住，还是先留一块安静。",
  "ELEVATOR|电梯停在陌生楼层|门打开时整面镜子先映出{name}。{city}的灯被留在背后，前方是一条只够两人并肩的暗廊。",
  "COAT CHECK|一张号码牌|外套被挂进第 27 格。你突然意识到，离开时必须回来取它——这让今晚像是被悄悄加了一个结尾。",
  "FIRST SIP|第一口比预想更复杂|{drink}先是酸，随后有一小段烟熏。你放慢速度，决定今晚每杯酒之间都加一杯水。",
  "WINDOW SEAT|窗边唯一空位|你坐下时正好看见一辆末班公交驶过。玻璃把{track}的鼓点震成细纹，城市在另一侧无声移动。",
  "DRESS CODE|鞋跟与门槛|门口没有评判你的穿着，只提醒你台阶很暗。你走进去，发现真正吸引视线的是你不慌不忙的步子。",
  "BAR STOOL|第七码高脚凳|吧台只剩一个位置，左右各坐着一位互不认识的人。你把手机扣在桌面，给今晚留出第一次真正抬头。",
  "BIRTHDAY|隔壁桌的生日|陌生人的生日歌只唱到一半就笑场。有人把一小块蛋糕分给你，奶油甜味意外地配上了{drink}。",
  "POWER CUT|灯暗了一秒|全场灯光短暂熄灭，只有应急出口和几十块手机屏幕亮着。灯回来时，所有人像共同保守了一个一秒钟的秘密。",
  "VINYL CRACKLE|唱针落下|DJ没有立刻接强拍，而是让黑胶的底噪先铺满房间。你听见身后有人准确说出这首歌的采样来源。",
  "NO SIGNAL|手机失去信号|地下空间没有网络。地图、消息和外卖同时离线，你只好记住出口，也更认真地看清眼前的人。",
  "MIRROR LINE|镜子里的第二入口|你以为前面没有路，直到镜中有人从暗门走出。{bar}像故意把现实折了一次。",
  "FRAGRANCE|一阵雪松香|有人经过时带起雪松与柑橘的气味，没有回头。几秒后，你在酒单里看到同样的风味组合。",
  "FIRST WATER|先来一杯水|调酒师没有急着推酒单，而是先放下一杯常温水。这份不动声色的照顾，让你决定在这里多待一会。",
  "QUEUE FRIEND|排队时的临时同盟|前面的人替你扶住快要合上的门。你们只聊了两分钟，却交换了各自在{city}最喜欢的深夜面馆。",
  "PHOTO BOOTH|无人使用的拍照亭|帘子半开，屏幕停在倒计时“3”。你可以拍一张只给自己看的照片，也可以把它留给下一位陌生人。",
  "EMPTY TABLE|被预留的空桌|服务员确认三次后说预订客人取消了。整张桌子归你，像城市今晚突然多给了一点空间。",
  "SOUND CHECK|低频还没完全打开|你到得比人群早，DJ正在校准监听。没有高潮的二十分钟反而让你看见工作人员如何把夜晚一块块搭起来。",
  "CITY VIEW|四十二层的风|电梯速度让耳膜轻轻一紧。落地窗外，车流像缓慢的电路；杯中的冰比整座城市更响。",
  "SECRET MENU|酒单最后一页|最后一页没有价格，只写三种情绪：靠近、转身、暂停。调酒师说它们都可以做成无酒精版本。",
  "LOST EARRING|地面的一点银光|你捡到一只小耳环交给吧台。十分钟后失主回来道谢，认真记住了你的名字。",
  "FLOWER SELLER|门外最后一束花|进门前有人问你要不要买今晚最后一束雏菊。你买下后把一半留给门口辛苦站岗的人。",
  "RESERVATION|名字被正确念出|接待准确念出{name}，没有问多余的问题。被认真对待的第一分钟，让肩膀先松了下来。",
  "FRESH ICE|第一块透明冰|冰块落杯的声音干净得像按下开始键。你看一眼时间：22:47，故事从这里正式计时。",
];
const P1 = [
  "EYE CONTACT|吧台另一端的两秒|你抬头时和一个人对视了两秒。对方先移开，又在{track}副歌开始时举杯示意；这可能是搭讪，也可能只是礼貌。",
  "SONG QUESTION|“你也喜欢这首？”|旁边的人指了指音箱问你。你听得出这不是背熟的开场白，因为对方还准确说出了制作人的名字。",
  "BARTENDER STORY|杯垫背面的地图|调酒师翻过杯垫，画出三条夜宵路线，并圈出自己下班后会去的一家。城市忽然有了私人注脚。",
  "OLD FRIEND|熟悉名字从身后响起|多年没见的同学认出你，身边还带着两个新朋友。过去与现在被迫坐到同一张桌上，但没有谁急着叙旧。",
  "WRONG DRINK|端错的一杯|服务员把一杯粉色长饮放到你面前，立刻发现桌号错了。真正的主人走来，两个人同时说“没关系”，然后笑了。",
  "DANCE CIRCLE|舞池让出一个圆|几个人为即兴舞步留出空间，没有起哄，也没有推人进去。有人向你伸手，但停在足够远的位置等你决定。",
  "QUIET CORNER|安静没有被打断|人群绕过你所在的角落。你听完整首{track}，发现独处并不是故事缺席，而是一种清楚的选择。",
  "PHONE CHARGER|借到最后一根线|邻座把充电线分给你一半，说自己还有 38%。你们把两部手机放在一起，却先聊起各自最近想逃离的通知。",
  "COASTER NOTE|杯垫上的一句话|上一位客人在杯垫背面写：“今晚别急着证明什么。”你不知道是谁留下，却决定把它收进口袋。",
  "GROUP PHOTO|被邀请按快门|一群朋友请你帮忙拍合照。你连续按了三张，第四张时他们把你也拉进画面，但先问你是否愿意。",
  "ACCENT|从口音猜城市|有人准确听出你不是本地人，却没有追问来历，只推荐一首属于他故乡的歌。你们交换的第一样东西是一段声音。",
  "ICE BREAKER|一块滚到脚边的冰|调酒师做 flair 时冰块意外落地，严肃的全场一起笑了。完美被打破后，陌生人之间反而更容易说话。",
  "BOOK ON BAR|吧台上的小说|有人在吵闹里读一本书，书脊是你也读过的作者。你可以谈书，也可以尊重这份独处。",
  "JACKET MIXUP|拿错的同款外套|两件黑色外套几乎一模一样。你们翻口袋确认归属，一个装着薄荷糖，一个装着电影票根。",
  "DRINK QUESTION|“这杯是什么味道？”|对方没有问你一个人来不来，只认真问{drink}。话题停留在风味，没有越过你没开放的边界。",
  "DJ REQUEST|一张点歌纸条|DJ 收下纸条却不保证会放。四十分钟后熟悉的前奏响起，递纸条的人隔着人群找到你的眼睛。",
  "LANGUAGE SWAP|一句不熟练的中文|旅行者努力念对{drink}的名字，你帮他纠正声调；作为交换，他教你一句自己家乡的晚安。",
  "RAIN RETURN|雨又开始了|窗边的人发现你没带伞，提出离开时可以送到地铁口，同时补了一句：“如果你觉得方便的话。”",
  "POLAROID|一张即时照片|摄影师问能否拍下你手边的杯子，不拍脸。成像后把唯一一张底片交给你，没有索要账号。",
  "SEAT OFFER|有人让出靠里位置|不是因为身高或性别，只因为那里更安静。微小的体贴没有附带谈话义务。",
  "NOISE APP|分贝提醒|手表震动提醒环境过响。旁边的人看到后指向走廊尽头的安静区，你们并肩走过去，仍保留一臂距离。",
  "PET VIDEO|最普通的破冰|陌生人给同伴看猫打翻水杯的视频，你没忍住笑出声。对方问要不要再看一个——艳遇可能从最不浪漫的东西开始。",
  "SAME ORDER|两杯同名酒|你和邻座同时点了{drink}。调酒师把杯子并排放下，你们各自先喝水，再比较第一口的感受。",
  "COMPLIMENT|一个具体的赞美|有人说喜欢你的耳饰配色，而不是评价身体。具体、轻巧、不索取回应，这句搭讪因此显得舒服。",
  "DECLINE|被好好接住的拒绝|有人邀请你去舞池，你说想先坐会儿。对方只回“当然”，没有追问。边界被尊重后，空气没有变坏。",
];
const P2 = [
  "DEEP TALK|话题越过寒暄|你们从{track}聊到最近一次想换城市的念头。对方没有急着给建议，只问：“那件事对你最难的是什么？”",
  "WATER BREAK|第二杯是气泡水|你把酒换成水，对方也跟着换了。清醒没有让暧昧降温，反而让每句话都更容易被记住。",
  "DANCE ASK|先问，再靠近|对方在音乐变快时问：“一起跳吗？不想也没关系。”伸出的手停在半空，选择权完整地留给你。",
  "FRIEND CHECK|朋友发来一个句号|这是你们约定的安全暗号。你回复定位和“都好”，顺手确认回程路线，心情因此更放松。",
  "EX TEXT|旧消息突然亮起|一个曾经很重要的人发来“睡了吗”。你没有立刻回复，把手机翻面，决定先完成眼前真实的夜晚。",
  "SPILLED DRINK|杯子被碰倒|酒液越过桌面，对方先拿纸巾护住你的手机，而不是责怪谁。狼狈被处理得很轻，距离也因此真实了一点。",
  "SLOW SONG|DJ 突然降速|强拍被一首慢歌切开，人群有些不知所措。你们可以继续跳、退到边缘，或各自给彼此空间。",
  "ROOFTOP AIR|天台的风让人清醒|你们走到户外区，门仍在视线内。{city}凌晨的风吹散酒气，谈话第一次不需要靠得很近。",
  "BAR SNACK|最后一份热食|厨房只剩一份小食，你们分开装在两个盘子里。分享不等于亏欠，账单也各自清楚。",
  "NAME AGAIN|再次确认名字|对方在嘈杂里重新问了一遍{name}，并认真念对。被记住的不是照片，而是你刚才讲的那件小事。",
  "BOUNDARY|手停在肩膀前|对方想替你拂去纸屑，却在碰到前先示意。你点头或摇头都很自然，暧昧不需要偷走同意。",
  "TWO TRUTHS|两个真话，不玩谎言|你们各说一件最近让自己开心的小事。不靠窥探隐私，话题也能逐渐靠近。",
  "MUSIC SHARE|一边耳机|安静区听不见 DJ，你们用一副耳机播放{track}。对方先擦了耳塞，再问你愿不愿意共享另一边。",
  "BAD JOKE|一个很冷的笑话|笑话并不好笑，但讲完后对方先自嘲。你真正喜欢的是那份不端着，而不是包袱本身。",
  "WORK CALL|突然的工作电话|对方接到紧急电话，回来后坦白今晚状态不适合继续社交。你们互相祝好，没有把中止解释成失败。",
  "LOST FRIEND|帮人找到同伴|一位明显慌张的客人找不到朋友。你和工作人员一起确认安全区域，十分钟后两人重逢，全场压力才松开。",
  "FLOOR CHANGE|换一层声音|你们从电子舞池走到爵士吧台，音量下降后发现彼此说话的速度也慢了。不同音乐像切换了另一条剧情线。",
  "TASTE TEST|盲闻三种香气|调酒师递来柚子、罗勒和烘烤可可让你们猜。答案都错了，但你们记住了彼此第一反应。",
  "SILENCE|十秒钟没人说话|沉默没有被急着填满。你们同时看向舞池，又同时笑了；舒服的空白也是化学反应的一部分。",
  "CHECK SPLIT|账单被自然分开|服务员问是否分单，两个人同时说“分开”。没有试探、没有表演，平等让接下来的靠近更轻松。",
  "COMPLIMENT RETURN|赞美被接住|你说喜欢对方讲故事时会先想两秒。对方没有否定自己，只说谢谢，然后也给你一个具体而不过界的赞美。",
  "PHOTO CONSENT|镜头举起前|朋友想记录舞池，先确认画面里的你是否介意。你可以加入，也可以退到镜头外，两种选择都被立刻接受。",
  "LAST ROUND|不再加酒|酒保提醒这是最后点单。你选择水和一份小食，保留判断力，也让身体跟上今晚的节奏。",
  "METRO CLOCK|末班车倒计时|手机显示还有 23 分钟。你们决定不靠错过交通制造浪漫，先把安全回程放进计划。",
  "ALMOST KISS|距离只剩半步|音乐和人群都像退远了，但没有人默认下一步。一个清楚的问题，比任何突然靠近都更有张力。",
];
const P3 = [
  "ASKED KISS|一句完整的问题|“我可以吻你吗？”问题被清楚说出，答案也有充分空间。无论点头还是说慢一点，这一刻都不需要猜。",
  "DAYLIGHT DATE|约在白天见|你们没有把凌晨的浓度当成承诺，只约了周日下午喝咖啡。能在阳光里继续的可能，显得更可靠。",
  "PLAYLIST|交换歌单|不是微信开场白，而是一张各自十首歌的清单。最后一首都留空，等下一次见面再补。",
  "GOODBYE ALONE|一个人叫车|你在明亮区域确认车牌，把行程分享给朋友。车门关上时没有失落，只有完整结束一晚的踏实。",
  "FRIENDS HOME|和朋友一起离开|你们在门口清点人数、外套和手机。最好的夜晚有时不是艳遇，而是所有人都平安到家。",
  "SUNRISE NOODLES|清晨第一碗面|你们去了调酒师画在杯垫上的店。没有继续喝酒，热汤让每个人慢慢回到真实世界。",
  "SOFT NO|“我想慢一点”|对方说还不想吻，你回答“当然”。边界没有破坏气氛，反而让这段相遇从幻想落到可信。",
  "MUTUAL YES|被回答的靠近|对方看着你点头，先确认彼此都清醒舒服。这个吻很短，像一首歌结束前最后一下鼓点。",
  "NUMBER LOST|号码没有保存成功|回到车上才发现联系人没有同步。遗憾很轻，却让这场相遇保留为一段只属于今晚的电影。",
  "WRONG NUMBER|最后一位写错|第二天消息没有送达。你没有回酒吧寻找，也没有责怪谁；有些故事的价值不靠续集证明。",
  "COAT RETURN|取回第 27 格外套|号码牌完成了使命。工作人员说晚安，你发现口袋里多了一张写着歌曲名的杯垫。",
  "RAIN WALK|共撑一把伞到地铁|伞并不大，你们先问好目的地，再保持舒服的距离。雨声替代低频，谈话终于不用喊。",
  "TAXI SPLIT|不同方向的两辆车|你们没有因为“顺路”勉强同乘。两辆车先后到达，隔着车窗挥手，安全比戏剧性更重要。",
  "NO PROMISE|没有说“永远联系”|你们只说今天很开心。克制的告别没有减少真诚，反而让这晚停在恰好的位置。",
  "VOICE NOTE|到家后的十秒语音|对方只说“我到了，谢谢今晚”。你回复同样简短的一句，确认安全后把手机调成勿扰。",
  "QUIET WIN|没有艳遇的好结局|你认真喝完一杯、听完几首歌，并在想走时离开。不是每个夜晚都要被另一个人证明。",
  "BARTENDER FAREWELL|记住你喝水的人|离开时调酒师把水杯推近，说路上小心。他记住的不是你喝了多少，而是你一直在照顾节奏。",
  "DAWN PHOTO|只拍城市，不拍人|你们在门口拍下四点的街道，没有把彼此放进镜头。照片不公开，先只留在各自手机里。",
  "BREAKFAST GROUP|陌生人变成一桌|最初互不认识的六个人拼桌吃早餐。没人追问关系，大家只认真讨论豆浆该甜还是咸。",
  "FOUND EARRING|耳环回到主人手里|失主在门口追上你，再次道谢。你们没有发展成爱情，却共同完成了一个小小的圆满。",
  "FIRST TRAIN|等到首班地铁|你在便利店买水，坐在明亮窗口等车。耳朵还残留低频，清晨的人群已经开始另一种生活。",
  "BLOCKED CHOICE|主动结束不舒服的对话|当对方开始越界追问，你清楚说不再继续并走向工作人员。故事没有浪漫结尾，但你保护了自己。",
  "STAFF HELP|安全计划被启动|工作人员陪你到等车区并记录异常情况。求助不是扫兴，而是让夜生活值得信任的基础设施。",
  "SECOND CITY|下次在另一座城|你们发现下月都会去同一场音乐节，只约好若行程仍合适就再联系，不提前制造承诺。",
  "MORNING SONG|最后一首成为第一首|回家路上{track}又随机播放。它不再只是热门曲目，而成了你记住{city}这一夜的私人坐标。",
];

const parse = (phase: number, item: string): StorySeed => {
  const [tag, title, text] = item.split("|");
  return { phase, tag, title, text };
};
export const STORY_SEEDS: StorySeed[] = [
  ...P0.map((x) => parse(0, x)), ...P1.map((x) => parse(1, x)),
  ...P2.map((x) => parse(2, x)), ...P3.map((x) => parse(3, x)),
];
